In [362]:
import pandas as pd
import numpy as np

In [479]:
df=pd.read_excel("/Users/sunitjadeja/Desktop/PandasData.xlsx")

In [486]:
df[df["corrected division"]=="LSI"]["corrected division"].value_counts()

LSI    26531
Name: corrected division, dtype: int64

In [484]:
df[df["industry segment"]>27]["industry segment"].unique()

array([ 47., 109., 111.,  63., 108.,  90.,  31.,  88.,  29.,  58.,  42.,
        82.,  38.,  30.,  65.,  96.,  56.,  79.,  87.,  34.,  76.,  53.,
        75.,  86., 112.,  73.,  83.,  84.,  69.,  91.,  33., 116.,  44.,
        74.,  57.,  68.,  80.,  37.,  81.,  67.,  93., 110.,  51.,  92.,
        43., 113.,  52.,  78.,  40.,  55.,  36.,  95.,  49.,  41., 114.,
        71.,  60.,  89.,  61.,  50.])

In [490]:
df1=df[~df["ship-to city"].isnull()]
df1[df1["ship-to city"].str.contains("Prade")]

,company code,equipment number,bill-to customer number,sold-to customer number,ship-to customer number,ship-to city,ship-to postal code,ship-to state,ship-to state name,industry segment,...,last contract line item,last contract header start date,last contract header end date,future contract line item,future contract header start date,future contract header end date,load_date,corrected division,logic date,logic_date
4589,2040,14831334,NaN,0001189697,0001189697,Uttar Pradesh,250609,UP,Uttar Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2017-05-29,2017-05-29
5295,2040,14852358,NaN,0001505098,0001505098,Himachal Pradesh,175126,HP,Himachal Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2018-12-20,2018-12-20
7793,2040,12591758,0001243633,0001243633,0001243633,Uttar Pradesh,251003,UP,Uttar Pradesh,11.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2012-11-22,2012-11-22
11330,2040,15789971,NaN,0001286609,0001286609,Andhra Pradesh,500007,TG,Telangana,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2019-04-04,2019-04-04
11752,2040,16530522,0001505098,0001505098,0001505098,Himachal Pradesh,175126,HP,Himachal Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,2020-07-12,2020-07-12
12384,2040,13419908,NaN,0001505641,0001505641,Uttar Pradesh,232101,UP,Uttar Pradesh,90.0,...,10.0,2017-02-16,2018-02-15,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2014-09-23,2014-09-23
13985,2040,13420122,NaN,0001243633,0001243633,Uttar Pradesh,251003,UP,Uttar Pradesh,11.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2014-09-23,2014-09-23
15072,2040,11712158,0001154403,0001154403,0001154403,Andhra Pradesh,533005,AP,Andhra Pradesh,6.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,2010-10-01,2010-10-01
17670,2040,14831335,NaN,0001189697,0001189697,Uttar Pradesh,250609,UP,Uttar Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2017-05-29,2017-05-29
18034,2040,14731946,NaN,0001139691,0001139691,Andhra Pradesh,533125,AP,Andhra Pradesh,11.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2017-03-16,2017-03-16
18098,2040,13420123,NaN,0001243633,0001243633,Uttar Pradesh,251003,UP,Uttar Pradesh,11.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2014-09-23,2014-09-23
18972,2040,14395748,NaN,0001335769,0001335769,Andra Pradesh,524344,AP,Andhra Pradesh,111.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,2016-06-24,2016-06-24
22454,2040,14112065,0001285896,0001285896,0001285896,Andhra Pradesh,500046,AP,Andhra Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2015-12-10,2015-12-10
25396,2040,14303068,0001286287,0001286287,0001286287,Andhra Pradesh,500007,AP,Andhra Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2016-04-21,2016-04-21
28899,2040,15739970,NaN,0001159523,0001159523,Uttar Pradesh,202389,UP,Uttar Pradesh,14.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2019-03-07,2019-03-07
29423,2040,12842762,0001286030,0001286030,0001286030,Andhra Pradesh,500046,AP,Andhra Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2013-08-09,2013-08-09
29574,2040,16284664,NaN,0001505098,0001505098,Himachal Pradesh,175126,HP,Himachal Pradesh,47.0,...,10.0,2021-04-01,2022-03-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,2019-12-12,2019-12-12
30704,2040,12445848,NaN,0001147370,0001147370,"Guntur, Andhra Pradesh",522001,AP,Andhra Pradesh,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2010-09-16,2010-09-16
32169,2040,12807865,NaN,0001223327,0001223327,Arunachal Pradesh,790101,ARP,Arunachal Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2013-04-24,2013-04-24
33213,2040,16596559,0001528480,0001528480,0001461327,Uttar Pradesh,211004,NaN,NaN,27.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2020-08-25,2020-08-25
35659,2040,14150211,0001327325,0001327325,0001327325,Himachal Pradesh,175001,HP,Himachal Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2015-12-14,2015-12-14
37973,2040,13695470,0001286229,0001286229,0001286229,Uttar Pradesh,221005,UP,Uttar Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2015-06-30,2015-06-30
40950,2040,13046561,0001286030,0001286030,0001286030,Andhra Pradesh,500046,AP,Andhra Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2013-11-07,2013-11-07
43504,2040,12578210,0001243633,0001243633,0001243633,Uttar Pradesh,251003,UP,Uttar Pradesh,11.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,2012-11-06,2012-11-06
44002,2040,16530521,0001505098,0001505098,0001505098,Himachal Pradesh,175126,HP,Himachal Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,2020-07-12,2020-07-12
51229,2040,13189183,0001286166,0001286166,0001286166,Andhra Pradesh,502324,AP,Andhra Pradesh,111.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2014-05-07,2014-05-07
52960,2040,12445812,NaN,0001147370,0001147370,"Guntur, Andhra Pradesh",522001,AP,Andhra Pradesh,NaN,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2010-09-16,2010-09-16
53774,2040,14924367,0001286609,0001286609,0001286609,Andhra Pradesh,500007,TG,Telangana,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2017-08-10,2017-08-10
54007,2040,12775629,NaN,0001223327,0001223327,Arunachal Pradesh,790101,ARP,Arunachal Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2013-05-06,2013-05-06
54483,2040,12842763,0001286030,0001286030,0001286030,Andhra Pradesh,500046,AP,Andhra Pradesh,47.0,...,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,2013-08-09,2013-08-09

In [499]:
df[(df["corrected division"]=="LSI") | (df["industry segment"]==27)]["corrected division"].unique()

array(['LSI', 'CMD', 'MOL', 'MSD', 'SDG', 'CAD', 'EPM', 'Unknown', 'MVS'],
      dtype=object)

In [500]:
LSI=df[df["corrected division"]=="LSI"]

In [501]:
CMD=df[df["corrected division"]=="CMD"]

In [502]:
LSI.shape

(26531, 68)

In [503]:
CMD.shape

(14612, 68)

In [506]:
26531+14612

41143

In [508]:
pd.concat([CMD,LSI],keys=["CMD","LSI"],axis=1)

               CMD                                           \
      company code equipment number bill-to customer number
0      hello world       17279051.0              0001146594
1             2040       17194740.0              0001665650
2             2040       17202899.0              0001509501
8             2040       17271465.0              0001657856
11            2040       17266956.0              0001288904
12            2040       17070621.0              0001137862
13            2040       17266952.0              0001288904
15            2040       17194746.0              0001665650
18            2040       15129412.0                     NaN
22            2040       17170861.0              0001506796
24            2040       17641723.0              0001141280
25            2040       17159153.0              0001661387
27            2040       17054405.0              0001589541
28            2040       17055240.0              0001506796
29            2040       13419863.0              0001138734
31            2040       17126419.0              0001509501
36            2040       13419594.0                     NaN
38            2040       16972377.0              0001574202
43            2040       16833222.0              0001137989
44            2040       17055247.0              0001506796
45            2040       17194747.0              0001665650
46            2040       17047898.0              0001177102
47            2040       17334509.0              0001506967
52            2040       13419839.0              0001138734
54            2040       17161984.0              0001661345
59            2040       17203007.0              0001509501
61            2040       17142003.0              0001541785
62            2040       16973021.0              0001574202
64            2040       13419853.0              0001138734
65            2040       17061388.0              0001137862
...            ...              ...                     ...
54516          NaN              NaN                     NaN
54518          NaN              NaN                     NaN
54519          NaN              NaN                     NaN
54520          NaN              NaN                     NaN
54522          NaN              NaN                     NaN
54524          NaN              NaN                     NaN
54525          NaN              NaN                     NaN
54526          NaN              NaN                     NaN
54529          NaN              NaN                     NaN
54530          NaN              NaN                     NaN
54532          NaN              NaN                     NaN
54533          NaN              NaN                     NaN
54534          NaN              NaN                     NaN
54538          NaN              NaN                     NaN
54539          NaN              NaN                     NaN
54540          NaN              NaN                     NaN
54541          NaN              NaN                     NaN
54543          NaN              NaN                     NaN
54544          NaN              NaN                     NaN
54546          NaN              NaN                     NaN
54548          NaN              NaN                     NaN
54549          NaN              NaN                     NaN
54552          NaN              NaN                     NaN
54553          NaN              NaN                     NaN
54555          NaN              NaN                     NaN
54557          NaN              NaN                     NaN
54558          NaN              NaN                     NaN
54560          NaN              NaN                     NaN
54561          NaN              NaN                     NaN
54562          NaN              NaN                     NaN

                                                                        \
      sold-to customer number ship-to customer number     ship-to city
0                  0001146594              0001146594       CHANDIGARH
1                  0001665650              0001665650        Hyderabad
2                  0001509501              0001509501         Vadodara
8                  0001657856              0001657856            HISAR
11                 0001288904              0001288904        HYDERABAD
12                 0001137862              0001137862        HYDERABAD
13                 0001288904              0001288904        HYDERABAD
15                 0001665650              0001665650        Hyderabad
18                 0001288925              0001288925           MUMBAI
22                 0001506796              0001506796        TELANGANA
24                 0001141280              0001141280        Bangalore
25                 0001661387              0001661387        Tuticorin
27                 0001589541              0001589541        HYDERABAD
28                 0001506796              0001506796        TELANGANA
29                 0001138734              0001138734           MUMBAI
31                 0001509501              0001509501         Vadodara
36                 0001288927              0001288927  PITHAMPUR, DHAR
38                 0001574202              0001574202         Srinagar
43                 0001137989              0001137989          GWALIOR
44                 0001506796              0001506796        TELANGANA
45                 0001665650              0001665650        Hyderabad
46                 0001177102              0001177102        BANGALORE
47                 0001506967              0001506967         RAMNAGAR
52                 0001138734              0001138734           MUMBAI
54                 0001661345              0001661345       Villupuram
59                 0001509501              0001509501         Vadodara
61                 0001541785              0001541785            Medak
62                 0001574202              0001574202         Srinagar
64                 0001138734              0001138734           MUMBAI
65                 0001137862              0001137862        HYDERABAD
...                       ...                     ...              ...
54516                     NaN                     NaN              NaN
54518                     NaN                     NaN              NaN
54519                     NaN                     NaN              NaN
54520                     NaN                     NaN              NaN
54522                     NaN                     NaN              NaN
54524                     NaN                     NaN              NaN
54525                     NaN                     NaN              NaN
54526                     NaN                     NaN              NaN
54529                     NaN                     NaN              NaN
54530                     NaN                     NaN              NaN
54532                     NaN                     NaN              NaN
54533                     NaN                     NaN              NaN
54534                     NaN                     NaN              NaN
54538                     NaN                     NaN              NaN
54539                     NaN                     NaN              NaN
54540                     NaN                     NaN              NaN
54541                     NaN                     NaN              NaN
54543                     NaN                     NaN              NaN
54544                     NaN                     NaN              NaN
54546                     NaN                     NaN              NaN
54548                     NaN                     NaN              NaN
54549                     NaN                     NaN              NaN
54552                     NaN                     NaN              NaN
54553                     NaN                     NaN              NaN
54555                     NaN                     NaN              NaN
54557                     NaN                     NaN              NaN
54558                     NaN                     NaN              NaN
54560                     NaN                     NaN              NaN
54561                     NaN                     NaN              NaN
54562                     NaN                     NaN              NaN

                                                                             \
      ship-to postal code ship-to state ship-to state name industry segment
0                  160012            CD         Chandigarh             47.0
1                  501401            TG          Telangana            109.0
2                  391450            GU            Gujarat             11.0
8                  125004            HR            Haryana            108.0
11                 500049            TG          Telangana             90.0
12                 500007            TG          Telangana             90.0
13                 500049            TG          Telangana             90.0
15                 501401            TG          Telangana            109.0
18                 400083            MH        Maharashtra             90.0
22                 500037            TG          Telangana             88.0
24                 560058            KA          Karnataka              6.0
25                 628501            TN         Tamil Nadu            108.0
27                 500078            TG          Telangana             90.0
28                 500037            TG          Telangana             88.0
29                 400079            MH        Maharashtra             90.0
31                 391450            GU            Gujarat             11.0
36                 454775            MP     Madhya Pradesh             90.0
38                 190001            JK  Jammu and Kashmir            108.0
43                 474002            MP     Madhya Pradesh             90.0
44                 500037            TG          Telangana             88.0
45                 501401            TG          Telangana            109.0
46                 560105            KA          Karnataka            111.0
47                 562112            KA          Karnataka              8.0
52                 400079            MH        Maharashtra             90.0
54                 605602            TN         Tamil Nadu            108.0
59                 391450            GU            Gujarat             11.0
61                 502307            TG          Telangana             90.0
62                 190001            JK  Jammu and Kashmir            108.0
64                 400079            MH        Maharashtra             90.0
65                 500007            TG          Telangana             90.0
...                   ...           ...                ...              ...
54516                 NaN           NaN                NaN              NaN
54518                 NaN           NaN                NaN              NaN
54519                 NaN           NaN                NaN              NaN
54520                 NaN           NaN                NaN              NaN
54522                 NaN           NaN                NaN              NaN
54524                 NaN           NaN                NaN              NaN
54525                 NaN           NaN                NaN              NaN
54526                 NaN           NaN                NaN              NaN
54529                 NaN           NaN                NaN              NaN
54530                 NaN           NaN                NaN              NaN
54532                 NaN           NaN                NaN              NaN
54533                 NaN           NaN                NaN              NaN
54534                 NaN           NaN                NaN              NaN
54538                 NaN           NaN                NaN              NaN
54539                 NaN           NaN                NaN              NaN
54540                 NaN           NaN                NaN              NaN
54541                 NaN           NaN                NaN              NaN
54543                 NaN           NaN                NaN              NaN
54544                 NaN           NaN                NaN              NaN
54546                 NaN           NaN                NaN              NaN
54548                 NaN           NaN                NaN              NaN
54549                 NaN           NaN                NaN              NaN
54552                 NaN           NaN                NaN              NaN
54553                 NaN           NaN                NaN              NaN
54555                 NaN           NaN                NaN              NaN
54557                 NaN           NaN                NaN              NaN
54558                 NaN           NaN                NaN              NaN
54560                 NaN           NaN                NaN              NaN
54561                 NaN           NaN                NaN              NaN
54562                 NaN           NaN                NaN              NaN

       ...                     LSI                                  \
       ... last contract line item last contract header start date
0      ...                     NaN                             NaT
1      ...                     NaN                             NaT
2      ...                     NaN                             NaT
8      ...                     NaN                             NaT
11     ...                     NaN                             NaT
12     ...                     NaN                             NaT
13     ...                     NaN                             NaT
15     ...                     NaN                             NaT
18     ...                     NaN                             NaT
22     ...                     NaN                             NaT
24     ...                     NaN                             NaT
25     ...                     NaN                             NaT
27     ...                     NaN                             NaT
28     ...                     NaN                             NaT
29     ...                     NaN                             NaT
31     ...                     NaN                             NaT
36     ...                     NaN                             NaT
38     ...                     NaN                             NaT
43     ...                     NaN                             NaT
44     ...                     NaN                             NaT
45     ...                     NaN                             NaT
46     ...                     NaN                             NaT
47     ...                     NaN                             NaT
52     ...                     NaN                             NaT
54     ...                     NaN                             NaT
59     ...                     NaN                             NaT
61     ...                     NaN                             NaT
62     ...                     NaN                             NaT
64     ...                     NaN                             NaT
65     ...                     NaN                             NaT
...    ...                     ...                             ...
54516  ...                     NaN                             NaT
54518  ...                     NaN                             NaT
54519  ...                    20.0                      2016-10-06
54520  ...                     NaN                             NaT
54522  ...                     NaN                             NaT
54524  ...                     NaN                             NaT
54525  ...                     NaN                             NaT
54526  ...                     NaN                             NaT
54529  ...                     NaN                             NaT
54530  ...                    80.0                      2015-09-01
54532  ...                     NaN                             NaT
54533  ...                     NaN                             NaT
54534  ...                     NaN                             NaT
54538  ...                    20.0                      2021-06-01
54539  ...                     NaN                             NaT
54540  ...                     NaN                             NaT
54541  ...                     NaN                             NaT
54543  ...                    10.0                      2017-03-15
54544  ...                     NaN                             NaT
54546  ...                     NaN                             NaT
54548  ...                    10.0                      2021-02-05
54549  ...                     NaN                             NaT
54552  ...                     NaN                             NaT
54553  ...                     NaN                             NaT
54555  ...                     NaN                             NaT
54557  ...                     NaN                             NaT
54558  ...                     NaN                             NaT
54560  ...                     NaN                             NaT
54561  ...                     NaN                             NaT
54562  ...                     NaN                             NaT

                                                               \
      last contract header end date future contract line item
0                               NaT                       NaN
1                               NaT                       NaN
2                               NaT                       NaN
8                               NaT                       NaN
11                              NaT                       NaN
12                              NaT                       NaN
13                              NaT                       NaN
15                              NaT                       NaN
18                              NaT                       NaN
22                              NaT                       NaN
24                              NaT                       NaN
25                              NaT                       NaN
27                              NaT                       NaN
28                              NaT                       NaN
29                              NaT                       NaN
31                              NaT                       NaN
36                              NaT                       NaN
38                              NaT                       NaN
43                              NaT                       NaN
44                              NaT                       NaN
45                              NaT                       NaN
46                              NaT                       NaN
47                              NaT                       NaN
52                              NaT                       NaN
54                              NaT                       NaN
59                              NaT                       NaN
61                              NaT                       NaN
62                              NaT                       NaN
64                              NaT                       NaN
65                              NaT                       NaN
...                             ...                       ...
54516                           NaT                       NaN
54518                           NaT                       NaN
54519                    2017-10-05                       NaN
54520                           NaT                       NaN
54522                           NaT                       NaN
54524                           NaT                       NaN
54525                           NaT                       NaN
54526                           NaT                       NaN
54529                           NaT                       NaN
54530                    2016-08-31                       NaN

# Creating Logic Date Column

In [541]:
df['logic date'] = df['equipment installed on'].fillna(df['equipment shipped date']).fillna(df['equipment created on'])



# df["logic_date"]=df["equipment installed on"]
# df['logic_date'].fillna(df['equipment shipped date'], inplace=True)
# df['logic_date'].fillna(df['equipment created on'], inplace=True)

In [377]:
df[["equipment installed on",'equipment shipped date','equipment created on',"logic_date"]]

,equipment installed on,equipment shipped date,equipment created on,logic_date
0,2021-11-26,NaT,2021-09-16,2021-11-26
1,NaT,NaT,NaT,NaT
2,NaT,NaT,NaT,NaT
3,2021-02-09,NaT,2020-06-15,2021-02-09
4,2021-06-24,NaT,2021-05-17,2021-06-24
5,2021-08-02,NaT,2020-07-29,2021-08-02
6,NaT,2022-05-01,2013-02-15,2022-05-01
7,2021-06-21,NaT,2020-04-25,2021-06-21
8,2021-11-09,NaT,2021-09-14,2021-11-09
9,NaT,NaT,2020-09-18,2020-09-18
10,2020-12-15,NaT,2019-12-13,2020-12-15
11,NaT,NaT,NaT,NaT
12,NaT,NaT,NaT,NaT
13,NaT,NaT,NaT,NaT
14,2021-03-11,NaT,2020-07-25,2021-03-11
15,NaT,NaT,NaT,NaT
16,NaT,2022-05-01,NaT,2022-05-01
17,NaT,NaT,NaT,NaT
18,NaT,2022-04-01,NaT,2022-04-01
19,NaT,2022-05-01,NaT,2022-05-01
20,2021-07-20,NaT,2021-06-08,2021-07-20
21,NaT,2020-06-26,2016-03-04,2020-06-26
22,2021-07-29,NaT,2021-07-14,2021-07-29
23,NaT,NaT,NaT,NaT
24,NaT,NaT,NaT,NaT
25,NaT,NaT,NaT,NaT
26,2017-08-21,2021-09-01,2017-11-02,2017-08-21
27,NaT,NaT,2021-05-04,2021-05-04
28,2021-06-24,NaT,2021-05-05,2021-06-24
29,NaT,2022-04-01,2014-09-23,2022-04-01
...,...,...,...,...
54533,2020-11-24,NaT,2020-07-11,2020-11-24
54534,NaT,NaT,2017-04-11,2017-04-11
54535,2015-07-01,NaT,2015-07-01,2015-07-01
54536,NaT,NaT,2014-10-21,2014-10-21
54537,2017-07-18,2022-04-01,2017-07-18,2017-07-18
54538,NaT,NaT,2019-04-25,2019-04-25
54539,NaT,NaT,2013-03-30,2013-03-30
54540,NaT,NaT,2018-12-06,2018-12-06
54541,2010-03-04,NaT,2012-08-24,2010-03-04
54542,NaT,NaT,2013-01-10,2013-01-10
54543,NaT,NaT,2016-02-14,2016-02-14
54544,2011-10-14,NaT,2011-06-18,2011-10-14
54545,NaT,NaT,2019-12-20,2019-12-20
54546,2021-09-29,NaT,2021-07-27,2021-09-29
54547,NaT,NaT,2021-09-15,2021-09-15
54548,NaT,NaT,2021-04-01,2021-04-01
54549,NaT,NaT,2018-01-05,2018-01-05
54550,NaT,NaT,2011-06-01,2011-06-01
54551,NaT,NaT,2016-06-02,2016-06-02
54552,2012-12-18,NaT,2013-03-25,2012-12-18
54553,2020-01-09,2021-01-09,2019-10-18,2020-01-09
54554,NaT,NaT,2018-03-27,2018-03-27
54555,2020-10-06,NaT,2020-08-25,2020-10-06
54556,2022-04-13,NaT,2022-01-13,2022-04-13
54557,2020-01-30,2022-01-30,2019-11-26,2020-01-30
54558,2020-08-21,NaT,2020-07-24,2020-08-21
54559,NaT,NaT,2020-09-04,2020-09-04
54560,2019-12-27,NaT,2020-01-20,2019-12-27
54561,2009-05-29,NaT,2012-11-02,2009-05-29
54562,NaT,NaT,2017-07-17,2017-07-17

In [542]:
df.dropna(subset="logic_date", inplace=True)
df.shape

(52449, 68)

# Removing Leading Zeroes From Columns

In [433]:
df.applymap(lambda s:s.lstrip('0') if type(s) == str else s)

,company code,equipment number,bill-to customer number,sold-to customer number,ship-to customer number,ship-to city,ship-to postal code,ship-to state,ship-to state name,industry segment,...,contract number of years,last contract number,last contract line item,last contract header start date,last contract header end date,future contract line item,future contract header start date,future contract header end date,load_date,corrected division
0,hello world,17279051,1146594,1146594,1146594,CHANDIGARH,160012,CD,Chandigarh,47.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-12-06,2023-12-05,2022-06-16 01:38:48.728,CMD
1,2040,17194740,1665650,1665650,1665650,Hyderabad,501401,TG,Telangana,109.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-09-21,2024-09-20,2022-06-16 01:38:48.728,CMD
2,2040,17202899,1509501,1509501,1509501,Vadodara,391450,GU,Gujarat,11.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-19,2026-07-18,2022-06-16 01:38:48.728,CMD
3,2040,16498250,1289243,1289243,1655354,Jammu,180004,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaN,NaT,NaT,30.0,2022-12-15,2025-12-14,2022-06-16 01:38:48.728,LSI
4,2040,17072866,1655736,1655736,1655736,PUNE,411007,MH,Maharashtra,19.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-08-28,2025-08-27,2022-06-16 01:38:48.728,LSI
5,2040,16556865,ICG2040,1464208,1142136,Jammu,180001,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaN,NaT,NaT,20.0,2023-08-02,2026-08-01,2022-06-16 01:38:48.728,LSI
6,2040,12679129,NaN,1129658,1216615,Kolkata,700156,WB,West Bengal,111.0,...,1.0,40322951.0,30.0,2021-05-01,2022-04-30,30.0,2023-05-01,2024-04-30,2022-06-16 01:38:48.728,LSI
7,2040,16438610,1140935,1140935,1140935,HYDERABAD,500078,TG,Telangana,63.0,...,NaN,NaN,NaN,NaT,NaT,20.0,2023-09-14,2024-09-13,2022-06-16 01:38:48.728,LSI
8,2040,17271465,1657856,1657856,1657856,HISAR,125004,HR,Haryana,108.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-10-30,2024-10-29,2022-06-16 01:38:48.728,CMD
9,2040,16644012,1289243,1289243,1641445,Srinagar,184140,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-05-19,2026-05-18,2022-06-16 01:38:48.728,LSI
10,2040,16285984,1629806,1629806,1629806,"SriCity,",517646,AP,Andhra Pradesh,6.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-08-05,2023-08-04,2022-06-16 01:38:48.728,LSI
11,2040,17266956,1288904,1288904,1288904,HYDERABAD,500049,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-12-19,2024-12-18,2022-06-16 01:38:48.728,CMD
12,2040,17070621,1137862,1137862,1137862,HYDERABAD,500007,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-16,2024-07-15,2022-06-16 01:38:48.728,CMD
13,2040,17266952,1288904,1288904,1288904,HYDERABAD,500049,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-12-19,2024-12-18,2022-06-16 01:38:48.728,CMD
14,2040,16550298,1598997,1598997,1210294,Kohima,797001,NG,Nagaland,27.0,...,NaN,NaN,NaN,NaT,NaT,20.0,2023-03-09,2024-03-08,2022-06-16 01:38:48.728,LSI
15,2040,17194746,1665650,1665650,1665650,Hyderabad,501401,TG,Telangana,109.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-09-30,2024-09-29,2022-06-16 01:38:48.728,CMD
16,2040,12679121,NaN,1129658,1216615,Kolkata,700156,WB,West Bengal,111.0,...,1.0,40322951.0,60.0,2021-05-01,2022-04-30,60.0,2023-05-01,2024-04-30,2022-06-16 01:38:48.728,LSI
17,2040,16634564,1478938,1478938,1638028,Raurkela,769005,OR,Orissa,111.0,...,NaN,NaN,NaN,NaT,NaT,40.0,2023-07-24,2024-07-23,2022-06-16 01:38:48.728,LSI
18,2040,15129412,NaN,1288925,1288925,MUMBAI,400083,MH,Maharashtra,90.0,...,0.5,40357809.0,100.0,2021-10-01,2022-03-31,100.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD
19,2040,12679123,NaN,1129658,1216615,Kolkata,700156,WB,West Bengal,111.0,...,1.0,40322951.0,30.0,2021-05-01,2022-04-30,30.0,2023-05-01,2024-04-30,2022-06-16 01:38:48.728,LSI
20,2040,17115466,1140073,1140073,1176026,Pune,411021,MH,Maharashtra,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2024-07-20,2026-09-07,2022-06-16 01:38:48.728,LSI
21,2040,14241242,1159371,1159371,1159371,KAHALGAON,813214,BI,Bihar,31.0,...,2.0,40244085.0,40.0,2018-04-01,2020-03-31,10.0,2022-06-26,2024-06-25,2022-06-16 01:38:48.728,EPM
22,2040,17170861,1506796,1506796,1506796,TELANGANA,500037,TG,Telangana,88.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-29,2024-07-28,2022-06-16 01:38:48.728,CMD
23,2040,16480231,1221643,1221643,1221643,JAIPUR,302004,RJ,Rajasthan,111.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-09-04,2024-09-03,2022-06-16 01:38:48.728,LSI
24,2040,17641723,1141280,1141280,1141280,Bangalore,560058,KA,Karnataka,6.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-08-13,2025-08-12,2022-06-16 01:38:48.728,CMD
25,2040,17159153,1661387,1661387,1661387,Tuticorin,628501,TN,Tamil Nadu,108.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-09-16,2024-09-15,2022-06-16 01:38:48.728,CMD
26,2040,15038954,1500896,1500896,1500896,Chanderia,312021,RJ,Rajasthan,111.0,...,1.0,40338834.0,10.0,2020-07-21,2021-07-20,10.0,2022-09-01,2023-08-31,2022-06-16 01:38:48.728,EPM
27,2040,17054405,1589541,1589541,1589541,HYDERABAD,500078,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-27,2024-07-26,2022-06-16 01:38:48.728,CMD
28,2040,17055240,1506796,1506796,1506796,TELANGANA,500037,TG,Telangana,88.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-08-05,2023-11-04,2022-06-16 01:38:48.728,CMD
29,2040,13419863,1138734,1138734,1138734,MUMBAI,400079,MH,Maharashtra,90.0,...,0.5,40357809.0,30.0,2021-10-01,2022-03-31,30.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54533,2040,16530345,1547016,1547016,1547016,Nagpur,441108,MH,Maharashtra,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54534,2040,14775067,1554215,1554215,1554215,Srinagar,190015,JK,Jammu and Kashmir,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54535,2040,13965054,1030068,1030068,1404808,"Kalyani Nagar, PUNE",411 014,NaN,NaN,63.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL
54536,2040,13473070,NaN,1189548,1189548,NAVI MUMBAI,400701,MH,Maharashtra,11.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54537,2040,14894283,1242918,1242918,1242918,PUNE,411021,MH,Maharashtra,90.0,...,1.0,40363524.0,20.0,2021-04-01,2022-03-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54538,2040,15821105,NaN,1242918,1242918,PUNE,411021,MH,Maharashtra,90.0,...,NaN,40374746.0,20.0,2021-06-01,2022-05-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54539,2040,12725733,NaN,1152094,1152094,HYDERABAD,500076,TG,Telangana,111.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54540,2040,15600615,1300205,1300205,1300205,PANCHWATI PUNE,411008,MH,Maharashtra,8.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54541,2040,12484748,NaN,1138797,1138797,JAMMU,180001,JK,Jammu and Kashmir,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54542,2040,12647255,1137858,1137858,1137858,KANPUR,208016,UP,Uttar Pradesh,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL
54543,2040,14210460,1146817,1146817,1146817,Imphal,795004,MN,Manipur,47.0,...,NaN,40202685.0,10.0,2017-03-15,2019-03-14,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54544,2040,12084275,1202889,1202889,1202889,GURGAON,122001,HR,Haryana,111.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54545,2040,16300531,1332016,1332016,1332016,MORAIYA,382213,GU,Gujarat,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54546,2040,17196936,1456078,1456078,1456078,Pune,411011,MH,Maharashtra,88.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54547,2040,17278258,1250700,1250700,1250700,NIMBAHERA,312601,RJ,Rajasthan,11.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM
54548,2040,17005743,1141204,1141204,1141204,Bangalore,560029,KA,Karnataka,88.0,...,NaN,40354727.0,10.0,2021-02-05,2022-02-04,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54549,2040,15123843,1566819,1566819,1566819,Chennai,600058,TN,Tamil Nadu,92.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54550,2040,12067819,1139911,1139911,1139911,KANPUR,208012,UP,Uttar Pradesh,90.0,...,NaN,40083773.0,10.0,2011-07-01,2012-06-30,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL
54551,2040,14366401,1138829,1138829,1138829,NAGAPATTINAM,611002,TN,Tamil Nadu,11.0,...,NaN,40134357.0,30.0,2013-12-02,2018-12-01,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM
54552,2040,12717436,NaN,1222454,1222454,Dhaka,1000,NaN,NaN,30.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54553,2040,16192628,1543368,1543368,1543368,Jammu,181143,JK,Jammu and Kashmir,47.0,...,2.0,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54554,2040,15218826,NaN,1445128,1550753,Champa,495688,CG,Chattisgarh,31.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CAD
54555,2040,16596803,1633219,1633219,1633219,Ahmedabad,382213,GU,Gujarat,86.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54556,2040,17474156,1676105,1676105,1676105,Vadodara,390021,GU,Gujarat,111.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54557,2040,16258226,NaN,1141462,1141462,LUCKNOW,226014,UP,Uttar Pradesh,90.0,...,3.0,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54558,2040,16549601,1141341,1141341,1141341,NEW DELHI,110067,DE,Delhi,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-10-24,2025-10-23,2022-06-16 01:38:48.728,LSI
54559,2040,16616453,1289273,1289273,1289273,GURGAON,122050,HR,Haryana,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54560,2040,16335107,NaN,1624691,1624691,Mumbai,400030,MH,Maharashtra,88.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54561,2040,12573049,NaN,1147571,1147571,New Delhi,110007,DE,Delhi,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54562,2040,14892414,NaN,1503727,1503727,Mahendragarh,123031,HR,Haryana,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI

In [435]:
df.dtypes

company code                                    object
equipment number                                 int64
bill-to customer number                         object
sold-to customer number                         object
ship-to customer number                         object
ship-to city                                    object
ship-to postal code                             object
ship-to state                                   object
ship-to state name                              object
industry segment                               float64
industry segment description                    object
customer classification                         object
customer class description                      object
industry code                                  float64
customer account type direct_asp                object
asp name                                        object
customer group code                             object
focus account                                   object
last end user contact telephone ism2            object
last end user contact mobile ism2               object
last end user contact email ism                 object
most used contact email ism2                    object
most used email count ism                      float64
equipment fse number                           float64
equipment model                                 object
equipment model name                            object
equipment material                              object
equipment material description                  object
equipment serial number                         object
sort field                                      object
                                             ...
sales office name                               object
equipment created on                    datetime64[ns]
equipment installed on                  datetime64[ns]
equipment system status                         object
equipment user status                           object
aag                                             object
aag description                                 object
warranty start date                             object
warranty end date                       datetime64[ns]
equipment usage                                 object
order reason                                    object
equipment status                                object
equipment shipped date                  datetime64[ns]
active contract header end date         datetime64[ns]
reference start date                            object
reference end date                      datetime64[ns]
extended warranty start date            datetime64[ns]
extended warranty end date              datetime64[ns]
active contract line value                     float64
active contract header value                   float64
contract number of years                       float64
last contract number                           float64
last contract line item                        float64
last contract header start date         datetime64[ns]
last contract header end date           datetime64[ns]
future contract line item                      float64
future contract header start date       datetime64[ns]
future contract header end date         datetime64[ns]
load_date                               datetime64[ns]
corrected division                              object
Length: 66, dtype: object

In [436]:
df.dropna(subset="bill-to customer number",inplace=True)
df["bill-to customer number"]=pd.to_numeric(df["bill-to customer number"], errors="coerce")

In [438]:
df.dtypes

company code                                    object
equipment number                                 int64
bill-to customer number                        float64
sold-to customer number                         object
ship-to customer number                         object
ship-to city                                    object
ship-to postal code                             object
ship-to state                                   object
ship-to state name                              object
industry segment                               float64
industry segment description                    object
customer classification                         object
customer class description                      object
industry code                                  float64
customer account type direct_asp                object
asp name                                        object
customer group code                             object
focus account                                   object
last end user contact telephone ism2            object
last end user contact mobile ism2               object
last end user contact email ism                 object
most used contact email ism2                    object
most used email count ism                      float64
equipment fse number                           float64
equipment model                                 object
equipment model name                            object
equipment material                              object
equipment material description                  object
equipment serial number                         object
sort field                                      object
                                             ...
sales office name                               object
equipment created on                    datetime64[ns]
equipment installed on                  datetime64[ns]
equipment system status                         object
equipment user status                           object
aag                                             object
aag description                                 object
warranty start date                             object
warranty end date                       datetime64[ns]
equipment usage                                 object
order reason                                    object
equipment status                                object
equipment shipped date                  datetime64[ns]
active contract header end date         datetime64[ns]
reference start date                            object
reference end date                      datetime64[ns]
extended warranty start date            datetime64[ns]
extended warranty end date              datetime64[ns]
active contract line value                     float64
active contract header value                   float64
contract number of years                       float64
last contract number                           float64
last contract line item                        float64
last contract header start date         datetime64[ns]
last contract header end date           datetime64[ns]
future contract line item                      float64
future contract header start date       datetime64[ns]
future contract header end date         datetime64[ns]
load_date                               datetime64[ns]
corrected division                              object
Length: 66, dtype: object

# With Regex Method Removing Leading Zeroes

In [370]:
# df['bill-to customer number']=df['bill-to customer number'].str.replace(r'^[0]*', '', regex=True).fillna('0')
# df['sold-to customer number']=df['sold-to customer number'].str.replace(r'^[0]*', '', regex=True).fillna('0')
# df["ship-to customer number"]=df['ship-to customer number'].str.replace(r'^[0]*', '', regex=True).fillna('0')

,company code,equipment number,bill-to customer number,sold-to customer number,ship-to customer number,ship-to city,ship-to postal code,ship-to state,ship-to state name,industry segment,...,contract number of years,last contract number,last contract line item,last contract header start date,last contract header end date,future contract line item,future contract header start date,future contract header end date,load_date,corrected division
0,hello world,17279051,1146594,1146594,1146594,CHANDIGARH,160012,CD,Chandigarh,47.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-12-06,2023-12-05,2022-06-16 01:38:48.728,CMD
1,2040,17194740,1665650,1665650,1665650,Hyderabad,501401,TG,Telangana,109.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-09-21,2024-09-20,2022-06-16 01:38:48.728,CMD
2,2040,17202899,1509501,1509501,1509501,Vadodara,391450,GU,Gujarat,11.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-19,2026-07-18,2022-06-16 01:38:48.728,CMD
3,2040,16498250,1289243,1289243,1655354,Jammu,180004,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaN,NaT,NaT,30.0,2022-12-15,2025-12-14,2022-06-16 01:38:48.728,LSI
4,2040,17072866,1655736,1655736,1655736,PUNE,411007,MH,Maharashtra,19.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-08-28,2025-08-27,2022-06-16 01:38:48.728,LSI
5,2040,16556865,ICG2040,1464208,1142136,Jammu,180001,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaN,NaT,NaT,20.0,2023-08-02,2026-08-01,2022-06-16 01:38:48.728,LSI
6,2040,12679129,NaN,1129658,1216615,Kolkata,700156,WB,West Bengal,111.0,...,1.0,40322951.0,30.0,2021-05-01,2022-04-30,30.0,2023-05-01,2024-04-30,2022-06-16 01:38:48.728,LSI
7,2040,16438610,1140935,1140935,1140935,HYDERABAD,500078,TG,Telangana,63.0,...,NaN,NaN,NaN,NaT,NaT,20.0,2023-09-14,2024-09-13,2022-06-16 01:38:48.728,LSI
8,2040,17271465,1657856,1657856,1657856,HISAR,125004,HR,Haryana,108.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-10-30,2024-10-29,2022-06-16 01:38:48.728,CMD
9,2040,16644012,1289243,1289243,1641445,Srinagar,184140,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-05-19,2026-05-18,2022-06-16 01:38:48.728,LSI
10,2040,16285984,1629806,1629806,1629806,"SriCity,",517646,AP,Andhra Pradesh,6.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-08-05,2023-08-04,2022-06-16 01:38:48.728,LSI
11,2040,17266956,1288904,1288904,1288904,HYDERABAD,500049,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-12-19,2024-12-18,2022-06-16 01:38:48.728,CMD
12,2040,17070621,1137862,1137862,1137862,HYDERABAD,500007,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-16,2024-07-15,2022-06-16 01:38:48.728,CMD
13,2040,17266952,1288904,1288904,1288904,HYDERABAD,500049,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-12-19,2024-12-18,2022-06-16 01:38:48.728,CMD
14,2040,16550298,1598997,1598997,1210294,Kohima,797001,NG,Nagaland,27.0,...,NaN,NaN,NaN,NaT,NaT,20.0,2023-03-09,2024-03-08,2022-06-16 01:38:48.728,LSI
15,2040,17194746,1665650,1665650,1665650,Hyderabad,501401,TG,Telangana,109.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-09-30,2024-09-29,2022-06-16 01:38:48.728,CMD
16,2040,12679121,NaN,1129658,1216615,Kolkata,700156,WB,West Bengal,111.0,...,1.0,40322951.0,60.0,2021-05-01,2022-04-30,60.0,2023-05-01,2024-04-30,2022-06-16 01:38:48.728,LSI
17,2040,16634564,1478938,1478938,1638028,Raurkela,769005,OR,Orissa,111.0,...,NaN,NaN,NaN,NaT,NaT,40.0,2023-07-24,2024-07-23,2022-06-16 01:38:48.728,LSI
18,2040,15129412,NaN,1288925,1288925,MUMBAI,400083,MH,Maharashtra,90.0,...,0.5,40357809.0,100.0,2021-10-01,2022-03-31,100.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD
19,2040,12679123,NaN,1129658,1216615,Kolkata,700156,WB,West Bengal,111.0,...,1.0,40322951.0,30.0,2021-05-01,2022-04-30,30.0,2023-05-01,2024-04-30,2022-06-16 01:38:48.728,LSI
20,2040,17115466,1140073,1140073,1176026,Pune,411021,MH,Maharashtra,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2024-07-20,2026-09-07,2022-06-16 01:38:48.728,LSI
21,2040,14241242,1159371,1159371,1159371,KAHALGAON,813214,BI,Bihar,31.0,...,2.0,40244085.0,40.0,2018-04-01,2020-03-31,10.0,2022-06-26,2024-06-25,2022-06-16 01:38:48.728,EPM
22,2040,17170861,1506796,1506796,1506796,TELANGANA,500037,TG,Telangana,88.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-29,2024-07-28,2022-06-16 01:38:48.728,CMD
23,2040,16480231,1221643,1221643,1221643,JAIPUR,302004,RJ,Rajasthan,111.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-09-04,2024-09-03,2022-06-16 01:38:48.728,LSI
24,2040,17641723,1141280,1141280,1141280,Bangalore,560058,KA,Karnataka,6.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2023-08-13,2025-08-12,2022-06-16 01:38:48.728,CMD
25,2040,17159153,1661387,1661387,1661387,Tuticorin,628501,TN,Tamil Nadu,108.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-09-16,2024-09-15,2022-06-16 01:38:48.728,CMD
26,2040,15038954,1500896,1500896,1500896,Chanderia,312021,RJ,Rajasthan,111.0,...,1.0,40338834.0,10.0,2020-07-21,2021-07-20,10.0,2022-09-01,2023-08-31,2022-06-16 01:38:48.728,EPM
27,2040,17054405,1589541,1589541,1589541,HYDERABAD,500078,TG,Telangana,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-07-27,2024-07-26,2022-06-16 01:38:48.728,CMD
28,2040,17055240,1506796,1506796,1506796,TELANGANA,500037,TG,Telangana,88.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-08-05,2023-11-04,2022-06-16 01:38:48.728,CMD
29,2040,13419863,1138734,1138734,1138734,MUMBAI,400079,MH,Maharashtra,90.0,...,0.5,40357809.0,30.0,2021-10-01,2022-03-31,30.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54533,2040,16530345,1547016,1547016,1547016,Nagpur,441108,MH,Maharashtra,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54534,2040,14775067,1554215,1554215,1554215,Srinagar,190015,JK,Jammu and Kashmir,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54535,2040,13965054,1030068,1030068,1404808,"Kalyani Nagar, PUNE",411 014,NaN,NaN,63.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL
54536,2040,13473070,NaN,1189548,1189548,NAVI MUMBAI,400701,MH,Maharashtra,11.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54537,2040,14894283,1242918,1242918,1242918,PUNE,411021,MH,Maharashtra,90.0,...,1.0,40363524.0,20.0,2021-04-01,2022-03-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54538,2040,15821105,NaN,1242918,1242918,PUNE,411021,MH,Maharashtra,90.0,...,NaN,40374746.0,20.0,2021-06-01,2022-05-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54539,2040,12725733,NaN,1152094,1152094,HYDERABAD,500076,TG,Telangana,111.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54540,2040,15600615,1300205,1300205,1300205,PANCHWATI PUNE,411008,MH,Maharashtra,8.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54541,2040,12484748,NaN,1138797,1138797,JAMMU,180001,JK,Jammu and Kashmir,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54542,2040,12647255,1137858,1137858,1137858,KANPUR,208016,UP,Uttar Pradesh,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL
54543,2040,14210460,1146817,1146817,1146817,Imphal,795004,MN,Manipur,47.0,...,NaN,40202685.0,10.0,2017-03-15,2019-03-14,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54544,2040,12084275,1202889,1202889,1202889,GURGAON,122001,HR,Haryana,111.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54545,2040,16300531,1332016,1332016,1332016,MORAIYA,382213,GU,Gujarat,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54546,2040,17196936,1456078,1456078,1456078,Pune,411011,MH,Maharashtra,88.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54547,2040,17278258,1250700,1250700,1250700,NIMBAHERA,312601,RJ,Rajasthan,11.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM
54548,2040,17005743,1141204,1141204,1141204,Bangalore,560029,KA,Karnataka,88.0,...,NaN,40354727.0,10.0,2021-02-05,2022-02-04,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54549,2040,15123843,1566819,1566819,1566819,Chennai,600058,TN,Tamil Nadu,92.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54550,2040,12067819,1139911,1139911,1139911,KANPUR,208012,UP,Uttar Pradesh,90.0,...,NaN,40083773.0,10.0,2011-07-01,2012-06-30,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL
54551,2040,14366401,1138829,1138829,1138829,NAGAPATTINAM,611002,TN,Tamil Nadu,11.0,...,NaN,40134357.0,30.0,2013-12-02,2018-12-01,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM
54552,2040,12717436,NaN,1222454,1222454,Dhaka,1000,NaN,NaN,30.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54553,2040,16192628,1543368,1543368,1543368,Jammu,181143,JK,Jammu and Kashmir,47.0,...,2.0,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54554,2040,15218826,NaN,1445128,1550753,Champa,495688,CG,Chattisgarh,31.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CAD
54555,2040,16596803,1633219,1633219,1633219,Ahmedabad,382213,GU,Gujarat,86.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54556,2040,17474156,1676105,1676105,1676105,Vadodara,390021,GU,Gujarat,111.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54557,2040,16258226,NaN,1141462,1141462,LUCKNOW,226014,UP,Uttar Pradesh,90.0,...,3.0,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54558,2040,16549601,1141341,1141341,1141341,NEW DELHI,110067,DE,Delhi,90.0,...,NaN,NaN,NaN,NaT,NaT,10.0,2022-10-24,2025-10-23,2022-06-16 01:38:48.728,LSI
54559,2040,16616453,1289273,1289273,1289273,GURGAON,122050,HR,Haryana,90.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD
54560,2040,16335107,NaN,1624691,1624691,Mumbai,400030,MH,Maharashtra,88.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54561,2040,12573049,NaN,1147571,1147571,New Delhi,110007,DE,Delhi,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI
54562,2040,14892414,NaN,1503727,1503727,Mahendragarh,123031,HR,Haryana,47.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI

# Ageing for Equipment Number

In [365]:
from datetime import datetime
import datetime as dt

In [544]:
df["Ageing of the product (in years)"]=(pd.to_datetime(datetime.now().date()) - df["logic_date"]).dt.days/365
df["Ageing of the product (in years)"]=df["Ageing of the product (in years)"].round(2)

# Cleaning Ship To City Column

In [403]:
city_cleaning_df=df[["ship-to city", "ship-to postal code"]]
city_cleaning_df.dropna(subset="ship-to postal code",inplace=True)

/var/folders/sy/lfmt7xdx3zj5qzj0mw834nzw0000gn/T/ipykernel_13756/2464619788.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_cleaning_df.dropna(subset="ship-to postal code",inplace=True)

In [518]:
# city_cleaning_df.dropna(subset="ship-to postal code",inplace=True)
city_cleaning_df['ship-to postal code']=pd.to_numeric(city_cleaning_df['ship-to postal code'],errors='coerce')

/var/folders/sy/lfmt7xdx3zj5qzj0mw834nzw0000gn/T/ipykernel_13756/4016888001.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  city_cleaning_df['ship-to postal code']=pd.to_numeric(city_cleaning_df['ship-to postal code'],errors='coerce')

In [528]:
# city_cleaning_df.dropna(subset="ship-to postal code",inplace=True)
df['ship-to postal code']=pd.to_numeric(df['ship-to postal code'],errors='coerce')

In [529]:
df.dropna(subset="ship-to postal code", inplace=True)

In [536]:
cleaned_city

,Circle Name,Region Name,Division Name,Office Name,Pincode,OfficeType,Delivery,District,StateName
0,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,A Narayanapuram B.O,515004,BO,Delivery,ANANTHAPUR,Andhra Pradesh
1,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Akuledu B.O,515731,BO,Delivery,ANANTHAPUR,Andhra Pradesh
2,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Alamuru B.O,515002,BO,Delivery,ANANTHAPUR,Andhra Pradesh
3,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Allapuram B.O,515766,BO,Delivery,ANANTHAPUR,Andhra Pradesh
4,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Aluru B.O,515415,BO,Delivery,ANANTHAPUR,Andhra Pradesh
5,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Amidyaya S.O,515822,SO,Delivery,ANANTHAPUR,Andhra Pradesh
6,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ammaladinne S.O,515445,SO,Delivery,ANANTHAPUR,Andhra Pradesh
7,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anantapur Collectorate S.O,515001,SO,Non Delivery,ANANTHAPUR,Andhra Pradesh
8,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anantapur Engg College S.O,515002,SO,Delivery,ANANTHAPUR,Andhra Pradesh
9,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anantapur H.O,515001,HO,Delivery,ANANTHAPUR,Andhra Pradesh
10,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ankampalli B.O,515741,BO,Delivery,ANANTHAPUR,Andhra Pradesh
11,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anumpalli B.O,515775,BO,Delivery,ANANTHAPUR,Andhra Pradesh
12,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Appecharla B.O,515455,BO,Delivery,ANANTHAPUR,Andhra Pradesh
13,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Appilepalli B.O,515766,BO,Delivery,ANANTHAPUR,Andhra Pradesh
14,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Arakatavemula B.O,515445,BO,Delivery,ANANTHAPUR,Andhra Pradesh
15,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Araveedu B.O,515465,BO,Delivery,ANANTHAPUR,Andhra Pradesh
16,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Aravindanagar S.O,515001,SO,Non Delivery,ANANTHAPUR,Andhra Pradesh
17,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Atmakur(ATP) S.O,515751,SO,Delivery,ANANTHAPUR,Andhra Pradesh
18,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Avuladatla B.O,515867,BO,Delivery,ANANTHAPUR,Andhra Pradesh
19,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Avulanna B.O,515741,BO,Delivery,ANANTHAPUR,Andhra Pradesh
20,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Aydukallu B.O,515763,BO,Delivery,ANANTHAPUR,Andhra Pradesh
21,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ayyagarlapalli B.O,515767,BO,Delivery,ANANTHAPUR,Andhra Pradesh
22,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ayyavaripalli B.O,515775,BO,Delivery,ANANTHAPUR,Andhra Pradesh
23,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ayyavaripalli B.O,515722,BO,Delivery,ANANTHAPUR,Andhra Pradesh
24,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,B.N.Halli B.O,515867,BO,Delivery,ANANTHAPUR,Andhra Pradesh
25,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,B.T.Project B.O,515863,BO,Delivery,ANANTHAPUR,Andhra Pradesh
26,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Bandameedapalli B.O,515722,BO,Delivery,ANANTHAPUR,Andhra Pradesh
27,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Bandlapalli B.O,515425,BO,Delivery,ANANTHAPUR,Andhra Pradesh
28,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Basapuram B.O,515766,BO,Delivery,ANANTHAPUR,Andhra Pradesh
29,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Basinepalli B.O,515402,BO,Delivery,ANANTHAPUR,Andhra Pradesh
...,...,...,...,...,...,...,...,...,...
155569,West Bengal Circle,South Bengal Region,Tamluk Division,Sitalpur BO,721632,BO,Delivery,EAST MIDNAPORE,West Bengal
155570,West Bengal Circle,South Bengal Region,Tamluk Division,Sitapur BO,721154,BO,Delivery,EAST MIDNAPORE,West Bengal
155571,West Bengal Circle,South Bengal Region,Tamluk Division,Sonachura BO,721646,BO,Delivery,EAST MIDNAPORE,West Bengal
155572,West Bengal Circle,South Bengal Region,Tamluk Division,Sreebora BO,721130,BO,Delivery,EAST MIDNAPORE,West Bengal
155573,West Bengal Circle,South Bengal Region,Tamluk Division,Srikantapur BO,721601,BO,Delivery,EAST MIDNAPORE,West Bengal
155574,West Bengal Circle,South Bengal Region,Tamluk Division,Srikantha BO,721629,BO,Delivery,EAST MIDNAPORE,West Bengal
155575,West Bengal Circle,South Bengal Region,Tamluk Division,Srikrishnapur BO,721659,BO,Delivery,EAST MIDNAPORE,West Bengal
155576,West Bengal Circle,South Bengal Region,Tamluk Division,Srirampur Mid SO,721651,SO,Delivery,EAST MIDNAPORE,West Bengal
155577,West Bengal Circle,South Bengal Region,Tamluk Division,Sudampur BO,721644,BO,Delivery,EAST MIDNAPORE,West Bengal
155578,West Bengal Circle,South Bengal Region,Tamluk Division,Sukrullapur BO,721626,BO,Delivery,EAST MIDNAPORE,West Bengal
155579,West Bengal Circle,South Bengal Region,Tamluk Division,Sulani BO,721158,BO,Delivery,EAST MIDNAPORE,West Bengal
155580,West Bengal Circle,South Bengal Region,Tamluk Division,Sulochanarambhadrapur BO,721651,BO,Delivery,EAST MIDNAPORE,West Bengal
155581,West Bengal Circle,South Bengal Region,Tamluk Division,Sultanpurbazar BO,721659,BO,Delivery,EAST MIDNAPORE,West Bengal
155582,West Bengal Circle,South Bengal Region,Tamluk Division,Sundarnagar BO,721634,BO,Delivery,EAST MIDNAPORE,West Bengal
155583,West Bengal Circle,South Bengal Region,Tamluk Division,Sutahata SO,721635,SO,Delivery,EAST MIDNAPORE,West Bengal
155584,West Bengal Circle,South Bengal Region,Tamluk Division,Tabakhali BO,721635,BO,Delivery,EAST MIDNAPORE,West Bengal
155585,West Bengal Circle,South Bengal Region,Tamluk Division,Tajnagar BO,721635,BO,Delivery,EAST MIDNAPORE,West Bengal
155586,West Bengal Circle,South Bengal Region,Tamluk Division,Tajpur BO,721656,BO,Delivery,EAST MIDNAPORE,West Bengal
155587,West Bengal Circle,South Bengal Region,Tamluk Division,Tamluk HO,721636,HO,Delivery,EAST MIDNAPORE,West Bengal
155588,West Bengal Circle,South Bengal Region,Tamluk Division,Teghorijoteviram BO,721627,BO,Delivery,EAST MIDNAPORE,West Bengal
155589,West Bengal Circle,South Bengal Region,Tamluk Division,Tekhalibazar SO,721646,SO,Delivery,EAST MIDNAPORE,West Bengal
155590,West Bengal Circle,South Bengal Region,Tamluk Division,Terapakhia SO,721656,SO,Delivery,EAST MIDNAPORE,West Bengal
155591,West Bengal Circle,South Bengal Region,Tamluk Division,Tilkhoja BO,721629,BO,Delivery,EAST MIDNAPORE,West Bengal
155592,West Bengal Circle,South Bengal Region,Tamluk Division,Tiorkhali BO,721655,BO,Delivery,EAST MIDNAPORE,West Bengal
155593,West Bengal Circle,South Bengal Region,Tamluk Division,Upalda BO,721152,BO,Delivery,EAST MIDNAPORE,West Bengal
155594,West Bengal Circle,South Bengal Region,Tamluk Division,Uttar Sautanchak BO,721649,BO,Delivery,EAST MIDNAPORE,West Bengal
155595,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarjianda BO,721151,BO,Delivery,EAST MIDNAPORE,West Bengal
155596,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarkotebarh BO,721626,BO,Delivery,EAST MIDNAPORE,West Bengal
155597,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarmechogram BO,721139,BO,Delivery,EAST MIDNAPORE,West Bengal
155598,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarsonamui BO,721648,BO,Delivery,EAST MIDNAPORE,West Bengal

In [538]:
df[["ship-to city", "ship-to postal code"]].merge(cleaned_city[["Pincode", "Division Name"]],left_on="ship-to postal code", right_on="Pincode",how="outer", indicator=True)

,ship-to city,ship-to postal code,Pincode,Division Name,_merge
0,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
1,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
2,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
3,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
4,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
5,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
6,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
7,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
8,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
9,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
10,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
11,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
12,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
13,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
14,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
15,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
16,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
17,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
18,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
19,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
20,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
21,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
22,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
23,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
24,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
25,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
26,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
27,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
28,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
29,CHANDIGARH,160012.0,160012.0,Chandigarh Division,both
...,...,...,...,...,...
437363,NaN,NaN,721130.0,Tamluk Division,right_only
437364,NaN,NaN,721130.0,Tamluk Division,right_only
437365,NaN,NaN,721646.0,Tamluk Division,right_only
437366,NaN,NaN,721646.0,Tamluk Division,right_only
437367,NaN,NaN,721646.0,Tamluk Division,right_only
437368,NaN,NaN,721646.0,Tamluk Division,right_only
437369,NaN,NaN,721646.0,Tamluk Division,right_only
437370,NaN,NaN,721646.0,Tamluk Division,right_only
437371,NaN,NaN,721646.0,Tamluk Division,right_only
437372,NaN,NaN,721607.0,Tamluk Division,right_only
437373,NaN,NaN,721607.0,Tamluk Division,right_only
437374,NaN,NaN,721604.0,Tamluk Division,right_only
437375,NaN,NaN,721625.0,Tamluk Division,right_only
437376,NaN,NaN,721625.0,Tamluk Division,right_only
437377,NaN,NaN,721625.0,Tamluk Division,right_only
437378,NaN,NaN,721625.0,Tamluk Division,right_only
437379,NaN,NaN,721625.0,Tamluk Division,right_only
437380,NaN,NaN,721153.0,Tamluk Division,right_only
437381,NaN,NaN,721153.0,Tamluk Division,right_only
437382,NaN,NaN,721153.0,Tamluk Division,right_only
437383,NaN,NaN,721153.0,Tamluk Division,right_only
437384,NaN,NaN,721153.0,Tamluk Division,right_only
437385,NaN,NaN,721655.0,Tamluk Division,right_only
437386,NaN,NaN,721655.0,Tamluk Division,right_only
437387,NaN,NaN,721655.0,Tamluk Division,right_only
437388,NaN,NaN,721655.0,Tamluk Division,right_only
437389,NaN,NaN,721655.0,Tamluk Division,right_only
437390,NaN,NaN,721655.0,Tamluk Division,right_only
437391,NaN,NaN,721171.0,Tamluk Division,right_only
437392,NaN,NaN,721624.0,Tamluk Division,right_only

0        160012.0
1        501401.0
2        391450.0
3        180004.0
4        411007.0
5        180001.0
6        700156.0
7        500078.0
8        125004.0
9        184140.0
10       517646.0
11       500049.0
12       500007.0
13       500049.0
14       797001.0
15       501401.0
16       700156.0
17       769005.0
18       400083.0
19       700156.0
20       411021.0
21       813214.0
22       500037.0
23       302004.0
24       560058.0
25       628501.0
26       312021.0
27       500078.0
28       500037.0
29       400079.0
           ...
54533    441108.0
54534    190015.0
54535         NaN
54536    400701.0
54537    411021.0
54538    411021.0
54539    500076.0
54540    411008.0
54541    180001.0
54542    208016.0
54543    795004.0
54544    122001.0
54545    382213.0
54546    411011.0
54547    312601.0
54548    560029.0
54549    600058.0
54550    208012.0
54551    611002.0
54552      1000.0
54553    181143.0
54554    495688.0
54555    382213.0
54556    390021.0
54557    226014.0
54558    110067.0
54559    122050.0
54560    400030.0
54561    110007.0
54562    123031.0
Name: ship-to postal code, Length: 53676, dtype: float64

In [526]:
cleaned_city.dtypes

Circle Name      object
Region Name      object
Division Name    object
Office Name      object
Pincode           int64
OfficeType       object
Delivery         object
District         object
StateName        object
dtype: object

In [407]:
city_cleaning_df["ship-to postal code"].nunique()

3612

In [408]:
city_cleaning_df["ship-to postal code"].value_counts()

560099.0    1343
500078.0     880
382210.0     530
396035.0     486
110067.0     477
411057.0     450
382213.0     438
400701.0     414
500090.0     378
500007.0     327
412115.0     326
110029.0     325
122001.0     311
411028.0     306
401506.0     303
560100.0     300
121001.0     277
500076.0     263
411007.0     260
560012.0     257
411008.0     238
400705.0     236
400076.0     229
122015.0     223
403722.0     218
560065.0     215
410208.0     201
396195.0     183
560066.0     178
391440.0     174
            ...
301701.0       1
591307.0       1
461001.0       1
474006.0       1
362315.0       1
796261.0       1
582208.0       1
784176.0       1
324007.0       1
608001.0       1
416217.0       1
637206.0       1
360560.0       1
781002.0       1
635113.0       1
680009.0       1
828104.0       1
400704.0       1
171201.0       1
457661.0       1
737111.0       1
144012.0       1
60005.0        1
484001.0       1
721645.0       1
441107.0       1
829110.0       1
631102.0       1
602602.0       1
507002.0       1
Name: ship-to postal code, Length: 3612, dtype: int64

In [410]:
city_cleaning_df[city_cleaning_df["ship-to postal code"]==500078]["ship-to city"].unique()

array(['HYDERABAD', 'Ranga Reddy', 'Hyderabad', 'Medchal',
       'Turkapally, Hyderabad', 'RANGA REDDY', 'Kolthur', 'HYDERABAD,',
       'Ranga Reddy District', 'Shameerpet', 'Telangana', 'RR DIST',
       'Turakapally (v)', 'Medak', 'Rangareddy', 'Malkajgri Dist',
       'Rengareddy', 'Shameerpet Mandal', 'Shameerpet Mandal, Hydrerabad',
       'QUTHBULLAPUR MANDAL', 'Hyderabad.', 'HYDEABAD', 'Medchal,',
       'MANDLA'], dtype=object)

In [520]:
cleaned_city=pd.read_csv("/Users/sunitjadeja/Desktop/AddressBook.csv",encoding='windows-1252')

In [521]:
cleaned_city#[cleaned_city["Pincode"]==560099]

,Circle Name,Region Name,Division Name,Office Name,Pincode,OfficeType,Delivery,District,StateName
0,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,A Narayanapuram B.O,515004,BO,Delivery,ANANTHAPUR,Andhra Pradesh
1,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Akuledu B.O,515731,BO,Delivery,ANANTHAPUR,Andhra Pradesh
2,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Alamuru B.O,515002,BO,Delivery,ANANTHAPUR,Andhra Pradesh
3,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Allapuram B.O,515766,BO,Delivery,ANANTHAPUR,Andhra Pradesh
4,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Aluru B.O,515415,BO,Delivery,ANANTHAPUR,Andhra Pradesh
5,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Amidyaya S.O,515822,SO,Delivery,ANANTHAPUR,Andhra Pradesh
6,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ammaladinne S.O,515445,SO,Delivery,ANANTHAPUR,Andhra Pradesh
7,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anantapur Collectorate S.O,515001,SO,Non Delivery,ANANTHAPUR,Andhra Pradesh
8,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anantapur Engg College S.O,515002,SO,Delivery,ANANTHAPUR,Andhra Pradesh
9,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anantapur H.O,515001,HO,Delivery,ANANTHAPUR,Andhra Pradesh
10,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ankampalli B.O,515741,BO,Delivery,ANANTHAPUR,Andhra Pradesh
11,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anumpalli B.O,515775,BO,Delivery,ANANTHAPUR,Andhra Pradesh
12,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Appecharla B.O,515455,BO,Delivery,ANANTHAPUR,Andhra Pradesh
13,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Appilepalli B.O,515766,BO,Delivery,ANANTHAPUR,Andhra Pradesh
14,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Arakatavemula B.O,515445,BO,Delivery,ANANTHAPUR,Andhra Pradesh
15,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Araveedu B.O,515465,BO,Delivery,ANANTHAPUR,Andhra Pradesh
16,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Aravindanagar S.O,515001,SO,Non Delivery,ANANTHAPUR,Andhra Pradesh
17,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Atmakur(ATP) S.O,515751,SO,Delivery,ANANTHAPUR,Andhra Pradesh
18,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Avuladatla B.O,515867,BO,Delivery,ANANTHAPUR,Andhra Pradesh
19,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Avulanna B.O,515741,BO,Delivery,ANANTHAPUR,Andhra Pradesh
20,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Aydukallu B.O,515763,BO,Delivery,ANANTHAPUR,Andhra Pradesh
21,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ayyagarlapalli B.O,515767,BO,Delivery,ANANTHAPUR,Andhra Pradesh
22,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ayyavaripalli B.O,515775,BO,Delivery,ANANTHAPUR,Andhra Pradesh
23,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ayyavaripalli B.O,515722,BO,Delivery,ANANTHAPUR,Andhra Pradesh
24,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,B.N.Halli B.O,515867,BO,Delivery,ANANTHAPUR,Andhra Pradesh
25,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,B.T.Project B.O,515863,BO,Delivery,ANANTHAPUR,Andhra Pradesh
26,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Bandameedapalli B.O,515722,BO,Delivery,ANANTHAPUR,Andhra Pradesh
27,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Bandlapalli B.O,515425,BO,Delivery,ANANTHAPUR,Andhra Pradesh
28,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Basapuram B.O,515766,BO,Delivery,ANANTHAPUR,Andhra Pradesh
29,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Basinepalli B.O,515402,BO,Delivery,ANANTHAPUR,Andhra Pradesh
...,...,...,...,...,...,...,...,...,...
155569,West Bengal Circle,South Bengal Region,Tamluk Division,Sitalpur BO,721632,BO,Delivery,EAST MIDNAPORE,West Bengal
155570,West Bengal Circle,South Bengal Region,Tamluk Division,Sitapur BO,721154,BO,Delivery,EAST MIDNAPORE,West Bengal
155571,West Bengal Circle,South Bengal Region,Tamluk Division,Sonachura BO,721646,BO,Delivery,EAST MIDNAPORE,West Bengal
155572,West Bengal Circle,South Bengal Region,Tamluk Division,Sreebora BO,721130,BO,Delivery,EAST MIDNAPORE,West Bengal
155573,West Bengal Circle,South Bengal Region,Tamluk Division,Srikantapur BO,721601,BO,Delivery,EAST MIDNAPORE,West Bengal
155574,West Bengal Circle,South Bengal Region,Tamluk Division,Srikantha BO,721629,BO,Delivery,EAST MIDNAPORE,West Bengal
155575,West Bengal Circle,South Bengal Region,Tamluk Division,Srikrishnapur BO,721659,BO,Delivery,EAST MIDNAPORE,West Bengal
155576,West Bengal Circle,South Bengal Region,Tamluk Division,Srirampur Mid SO,721651,SO,Delivery,EAST MIDNAPORE,West Bengal
155577,West Bengal Circle,South Bengal Region,Tamluk Division,Sudampur BO,721644,BO,Delivery,EAST MIDNAPORE,West Bengal
155578,West Bengal Circle,South Bengal Region,Tamluk Division,Sukrullapur BO,721626,BO,Delivery,EAST MIDNAPORE,West Bengal
155579,West Bengal Circle,South Bengal Region,Tamluk Division,Sulani BO,721158,BO,Delivery,EAST MIDNAPORE,West Bengal
155580,West Bengal Circle,South Bengal Region,Tamluk Division,Sulochanarambhadrapur BO,721651,BO,Delivery,EAST MIDNAPORE,West Bengal
155581,West Bengal Circle,South Bengal Region,Tamluk Division,Sultanpurbazar BO,721659,BO,Delivery,EAST MIDNAPORE,West Bengal
155582,West Bengal Circle,South Bengal Region,Tamluk Division,Sundarnagar BO,721634,BO,Delivery,EAST MIDNAPORE,West Bengal
155583,West Bengal Circle,South Bengal Region,Tamluk Division,Sutahata SO,721635,SO,Delivery,EAST MIDNAPORE,West Bengal
155584,West Bengal Circle,South Bengal Region,Tamluk Division,Tabakhali BO,721635,BO,Delivery,EAST MIDNAPORE,West Bengal
155585,West Bengal Circle,South Bengal Region,Tamluk Division,Tajnagar BO,721635,BO,Delivery,EAST MIDNAPORE,West Bengal
155586,West Bengal Circle,South Bengal Region,Tamluk Division,Tajpur BO,721656,BO,Delivery,EAST MIDNAPORE,West Bengal
155587,West Bengal Circle,South Bengal Region,Tamluk Division,Tamluk HO,721636,HO,Delivery,EAST MIDNAPORE,West Bengal
155588,West Bengal Circle,South Bengal Region,Tamluk Division,Teghorijoteviram BO,721627,BO,Delivery,EAST MIDNAPORE,West Bengal
155589,West Bengal Circle,South Bengal Region,Tamluk Division,Tekhalibazar SO,721646,SO,Delivery,EAST MIDNAPORE,West Bengal
155590,West Bengal Circle,South Bengal Region,Tamluk Division,Terapakhia SO,721656,SO,Delivery,EAST MIDNAPORE,West Bengal
155591,West Bengal Circle,South Bengal Region,Tamluk Division,Tilkhoja BO,721629,BO,Delivery,EAST MIDNAPORE,West Bengal
155592,West Bengal Circle,South Bengal Region,Tamluk Division,Tiorkhali BO,721655,BO,Delivery,EAST MIDNAPORE,West Bengal
155593,West Bengal Circle,South Bengal Region,Tamluk Division,Upalda BO,721152,BO,Delivery,EAST MIDNAPORE,West Bengal
155594,West Bengal Circle,South Bengal Region,Tamluk Division,Uttar Sautanchak BO,721649,BO,Delivery,EAST MIDNAPORE,West Bengal
155595,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarjianda BO,721151,BO,Delivery,EAST MIDNAPORE,West Bengal
155596,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarkotebarh BO,721626,BO,Delivery,EAST MIDNAPORE,West Bengal
155597,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarmechogram BO,721139,BO,Delivery,EAST MIDNAPORE,West Bengal
155598,West Bengal Circle,South Bengal Region,Tamluk Division,Uttarsonamui BO,721648,BO,Delivery,EAST MIDNAPORE,West Bengal

In [533]:
mapped=cleaned_city.merge(city_cleaning_df, left_on="Pincode", right_on="ship-to postal code",how="outer",indicator=True)
mapped

,Circle Name,Region Name,Division Name,Office Name,Pincode,OfficeType,Delivery,District,StateName,ship-to city,ship-to postal code,_merge
0,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,A Narayanapuram B.O,515004.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
1,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Georgepet S.O,515004.0,SO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
2,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Kakkalapalli Colony B.O,515004.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
3,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Motilal Street S.O,515004.0,SO,Non Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
4,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Narasanenikunta B.O,515004.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
5,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Rachanapalli B.O,515004.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
6,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Rajiv Colony B.O,515004.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
7,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Ramnagar S.O (Ananthapur),515004.0,SO,Non Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
8,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Rudrampeta B.O,515004.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
9,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Somaladoddi B.O,515004.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
10,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Tapovanagar B.O,515004.0,BO,Non Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
11,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Akuledu B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
12,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Garladinne S.O,515731.0,SO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
13,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Guddalapalli B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
14,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Jambuladinne B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
15,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Kanampalli B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
16,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Kotanka B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
17,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Kothapalli B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
18,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,M.P.R.Site B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
19,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Marthadu B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
20,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Penakacherla B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
21,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Podaralla B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
22,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Taticherla B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
23,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Thimmampeta B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
24,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Vadiampeta B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
25,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Yerraguntla B.O,515731.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,NaN,NaN,left_only
26,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Alamuru B.O,515002.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,Anand,515002.0,both
27,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Anantapur Engg College S.O,515002.0,SO,Delivery,ANANTHAPUR,Andhra Pradesh,Anand,515002.0,both
28,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Bramhanayaleru B.O,515002.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,Anand,515002.0,both
29,Andhra Pradesh Circle,Kurnool Region,Anantapur Division,Bukkacherla B.O,515002.0,BO,Delivery,ANANTHAPUR,Andhra Pradesh,Anand,515002.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...
438470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BANGALORE,580019.0,right_only
438471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Panchmahal,389351.0,right_only
438472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SRI LANKA,200.0,right_only
438473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GENOVA,16163.0,right_only
438474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sangareddy,502330.0,right_only
438475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sangareddy,502330.0,right_only
438476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HOSHIARPUR-DISTT,144203.0,right_only
438477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyderabad,500409.0,right_only
438478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ranchi,853303.0,right_only
438479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Meenabakkam,600027.0,right_only
438480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Makwanpur,44100.0,right_only
438481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,海口,570311.0,right_only
438482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pune,411000.0,right_only
438483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pune,411000.0,right_only
438484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COLUMBUS,43210.0,right_only
438485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Surat,395101.0,right_only
438486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Itanagar,79110.0,right_only
438487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GENOVA,16100.0,right_only
438488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deogarh,814419.0,right_only
438489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thimphu,11001.0,right_only
438490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CLERMONT FERRAND,63000.0,right_only
438491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shanghai,200082.0,right_only
438492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VISHAKHAPATNAM,631173.0,right_only
438493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JAIPUR,302023.0,right_only
438494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kochi,683509.0,right_only
438495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CHENNAI,600079.0,right_only
438496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ahmedabad,380081.0,right_only
438497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Navi Mumbai,4000703.0,right_only
438498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BAGALKOTE,680051.0,right_only
438499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PHARR,78577.0,right_only

In [534]:
# mapped=cleaned_city.merge(city_cleaning_df, on="Pincode",how="outer",indicator=True)
# mapped

In [ ]:
df["columns name"]=df["age in days"]/365

In [545]:
df["US Dollars"]=np.random.randint(1000,100000,size=len(df))

In [552]:
df.groupby(["corrected division"])[["US Dollars"]].sum()

                    US Dollars
corrected division
CAD                   93652048
CMD                  713476322
DIO                     342112
EM                       45697
EPM                  215030266
LSI                 1293299002
MOL                  208727662
MSD                   59339389
MVS                   28219175
SDG                   10783120
SID                      36836
Unknown               26074125

In [554]:
df.groupby(["corrected division", "equipment model name"])[["US Dollars","Ageing of the product (in years)"]].sum()

                                         US Dollars  \
corrected division equipment model name
CAD                1DEFENDER RMX              96807
                   3500TL DOSIMETRY           94464
                   3500TLD READER            474212
                   3500TLD READER INSTR       64459
                   900E TUBE GM6.0CM2        248333
                   ALLOY ANALYZER 100G       721140
                   ALLOY ANALYZER 800       1809791
                   ASMIVSCU 2SINGLE RDM       93051
                   AUTO SCRAP MONITOR        127703
                   BARGRAGRAPH COALBUNK     2674847
                   BARGRAGRAPH M-SYS         534867
                   BELT SCALE               6404067
                   BELT WEIGHER              112404
                   BIN WEIGHING               39774
                   C-LEVEL INDICATOR        1424902
                   CBOMNI1 ANALYZER          554062
                   CBX ANALYZER             3950838
                   CBX ANALYZER COAL         256027
                   CCMNBR AMPLIFIER PCB      133069
                   CEMENT ANALYZER            20611
                   CHARGER DXL                83831
                   CK101 PANEL                50534
                   COAL SAMPLING SYS          29634
                   COATING WEIGHT GAUGE       40327
                   CONT C LVL                250049
                   CONTAMINATION MONITR      164801
                   CQM ANALYZER               56219
                   CQM COAL QUALITY           76356
                   CTRL PANEL 9105P           22419
                   CTRLUT FHT6020            607849
...                                             ...
Unknown            HPLC-U3000                 47617
                   High Perf LR&F             71191
                   ICS6000                   120513
                   LCMS-Altis                 69585
                   LCMS-OT                    35243
                   LN2 Cryo                   20263
                   LSMS                        2492
                   MULTIGAS CALIBRATOR        37637
                   Micro Centrifuge          234216
                   NANODROP LITE              37070
                   NANODROP ONEC              92238
                   NOX ANALYZER               30258
                   OZONE ANALYZER             73350
                   Oven                       43431
                   PM 10 ANALYZER             87629
                   PROBE FHZ621              717106
                   RADEYE B20 H10 GAMMA      111169
                   RADEYE PX/WENDI N0         58981
                   Remote Monitoring Sy       19677
                   SO2 ANALYZER               78010
                   SOFTWARE                   47190
                   Stirrer                   148122
                   TRACE GC                   12034
                   Trace GC                   47975
                   TraceGC-AS                 41311
                   ULT Freezer               155731
                   UV-VIS SPECTROPHOMTR        4951
                   Value Enhanced LR&F        11578
                   Water Purification        146941
                   iCAP6300-D                104155

                                         Ageing of the product (in years)
corrected division equipment model name
CAD                1DEFENDER RMX                                    10.11
                   3500TL DOSIMETRY                                  5.15
                   3500TLD READER                                   36.83
                   3500TLD READER INSTR                              9.65
                   900E TUBE GM6.0CM2                               16.32
                   ALLOY ANALYZER 100G                              54.04
                   ALLOY ANALYZER 800                              261.64
                   ASMIVSCU 2SINGLE RDM                              7.33
                   AUTO SCRAP MONITOR                                9.69
                   BARGRAGRAPH COALBUNK                            238.52
                   BARGRAGRAPH M-SYS                                56.08
                   BELT SCALE                                      719.19
                   BELT WEIGHER                                     12.02
                   BIN WEIGHING                                      1.34
                   C-LEVEL INDICATOR                               192.90
                   CBOMNI1 ANALYZER                                 46.57
                   CBX ANALYZER                                    536.74
                   CBX ANALYZER COAL                                21.78
                   CCMNBR AMPLIFIER PCB                             11.26
                   CEMENT ANALYZER                                   1.73
                   CHARGER DXL                                       7.92
                   CK101 PANEL                                       7.90
                   COAL SAMPLING SYS                                 1.76
                   COATING WEIGHT GAUGE                              1.56
                   CONT C LVL                                       23.18
                   CONTAMINATION MONITR                             14.14
                   CQM ANALYZER                                     29.82
                   CQM COAL QUALITY                                  8.20
                   CTRL PANEL 9105P                                  6.01
                   CTRLUT FHT6020                                   52.02
...                                                                   ...
Unknown            HPLC-U3000                                       13.44
                   High Perf LR&F                                    2.74
                   ICS6000                                           4.59
                   LCMS-Altis                                        2.18
                   LCMS-OT                                          11.49
                   LN2 Cryo                                          1.35
                   LSMS                                             11.25
                   MULTIGAS CALIBRATOR                               3.58
                   Micro Centrifuge                                 15.62
                   NANODROP LITE                                     9.76
                   NANODROP ONEC                                     1.49
                   NOX ANALYZER                                      1.38
                   OZONE ANALYZER                                    4.36
                   Oven                                              1.26
                   PM 10 ANALYZER                                    4.86
                   PROBE FHZ621                                     73.58
                   RADEYE B20 H10 GAMMA                             12.22
                   RADEYE PX/WENDI N0                               12.30
                   Remote Monitoring Sy                              3.42
                   SO2 ANALYZER                                      1.38
                   SOFTWARE                                         20.59
                   Stirrer                                           6.90
                   TRACE GC                                          1.33
                   Trace GC                                          1.94
                   TraceGC-AS                                       11.05
                   ULT Freezer                                       4.21
                   UV-VIS SPECTROPHOMTR                              1.65
                   Value Enhanced LR&F                               1.54
                   Water Purification                               13.08
                   iCAP6300-D                                       32.74

[820 rows x 2 columns]

In [556]:
df.groupby(["corrected division", "equipment model name"]).agg({"US Dollars":"sum","Ageing of the product (in years)": np.mean,"ship-to city": "unique"})

                                         US Dollars  \
corrected division equipment model name
CAD                1DEFENDER RMX              96807
                   3500TL DOSIMETRY           94464
                   3500TLD READER            474212
                   3500TLD READER INSTR       64459
                   900E TUBE GM6.0CM2        248333
                   ALLOY ANALYZER 100G       721140
                   ALLOY ANALYZER 800       1809791
                   ASMIVSCU 2SINGLE RDM       93051
                   AUTO SCRAP MONITOR        127703
                   BARGRAGRAPH COALBUNK     2674847
                   BARGRAGRAPH M-SYS         534867
                   BELT SCALE               6404067
                   BELT WEIGHER              112404
                   BIN WEIGHING               39774
                   C-LEVEL INDICATOR        1424902
                   CBOMNI1 ANALYZER          554062
                   CBX ANALYZER             3950838
                   CBX ANALYZER COAL         256027
                   CCMNBR AMPLIFIER PCB      133069
                   CEMENT ANALYZER            20611
                   CHARGER DXL                83831
                   CK101 PANEL                50534
                   COAL SAMPLING SYS          29634
                   COATING WEIGHT GAUGE       40327
                   CONT C LVL                250049
                   CONTAMINATION MONITR      164801
                   CQM ANALYZER               56219
                   CQM COAL QUALITY           76356
                   CTRL PANEL 9105P           22419
                   CTRLUT FHT6020            607849
...                                             ...
Unknown            HPLC-U3000                 47617
                   High Perf LR&F             71191
                   ICS6000                   120513
                   LCMS-Altis                 69585
                   LCMS-OT                    35243
                   LN2 Cryo                   20263
                   LSMS                        2492
                   MULTIGAS CALIBRATOR        37637
                   Micro Centrifuge          234216
                   NANODROP LITE              37070
                   NANODROP ONEC              92238
                   NOX ANALYZER               30258
                   OZONE ANALYZER             73350
                   Oven                       43431
                   PM 10 ANALYZER             87629
                   PROBE FHZ621              717106
                   RADEYE B20 H10 GAMMA      111169
                   RADEYE PX/WENDI N0         58981
                   Remote Monitoring Sy       19677
                   SO2 ANALYZER               78010
                   SOFTWARE                   47190
                   Stirrer                   148122
                   TRACE GC                   12034
                   Trace GC                   47975
                   TraceGC-AS                 41311
                   ULT Freezer               155731
                   UV-VIS SPECTROPHOMTR        4951
                   Value Enhanced LR&F        11578
                   Water Purification        146941
                   iCAP6300-D                104155

                                         Ageing of the product (in years)  \
corrected division equipment model name
CAD                1DEFENDER RMX                                 5.055000
                   3500TL DOSIMETRY                              5.150000
                   3500TLD READER                                4.603750
                   3500TLD READER INSTR                          4.825000
                   900E TUBE GM6.0CM2                            5.440000
                   ALLOY ANALYZER 100G                           4.912727
                   ALLOY ANALYZER 800                            6.708718
                   ASMIVSCU 2SINGLE RDM                          7.330000
                   AUTO SCRAP MONITOR                            4.845000
                   BARGRAGRAPH COALBUNK                          4.969167
                   BARGRAGRAPH M-SYS                             7.010000
                   BELT SCALE                                    5.618672
                   BELT WEIGHER                                  6.010000
                   BIN WEIGHING                                  1.340000
                   C-LEVEL INDICATOR                             7.419231
                   CBOMNI1 ANALYZER                              4.657000
                   CBX ANALYZER                                  7.062368
                   CBX ANALYZER COAL                             5.445000
                   CCMNBR AMPLIFIER PCB                          5.630000
                   CEMENT ANALYZER                               1.730000
                   CHARGER DXL                                   7.920000
                   CK101 PANEL                                   7.900000
                   COAL SAMPLING SYS                             1.760000
                   COATING WEIGHT GAUGE                          1.560000
                   CONT C LVL                                    3.863333
                   CONTAMINATION MONITR                          4.713333
                   CQM ANALYZER                                 14.910000
                   CQM COAL QUALITY                              8.200000
                   CTRL PANEL 9105P                              6.010000
                   CTRLUT FHT6020                                5.780000
...                                                                   ...
Unknown            HPLC-U3000                                    6.720000
                   High Perf LR&F                                1.370000
                   ICS6000                                       2.295000
                   LCMS-Altis                                    2.180000
                   LCMS-OT                                      11.490000
                   LN2 Cryo                                      1.350000
                   LSMS                                         11.250000
                   MULTIGAS CALIBRATOR                           3.580000
                   Micro Centrifuge                              5.206667
                   NANODROP LITE                                 9.760000
                   NANODROP ONEC                                 1.490000
                   NOX ANALYZER                                  1.380000
                   OZONE ANALYZER                                4.360000
                   Oven                                          1.260000
                   PM 10 ANALYZER                                4.860000
                   PROBE FHZ621                                  6.131667
                   RADEYE B20 H10 GAMMA                          6.110000
                   RADEYE PX/WENDI N0                            6.150000
                   Remote Monitoring Sy                          1.710000
                   SO2 ANALYZER                                  1.380000
                   SOFTWARE                                     10.295000
                   Stirrer                                       1.380000
                   TRACE GC                                      1.330000
                   Trace GC                                      1.940000
                   TraceGC-AS                                   11.050000
                   ULT Freezer                                   1.403333
                   UV-VIS SPECTROPHOMTR                          1.650000
                   Value Enhanced LR&F                           1.540000
                   Water Purification                            6.540000
                   iCAP6300-D                                   10.913333

                                                                              ship-to city
corrected division equipment model name
CAD                1DEFENDER RMX                                       [Dhaka, Bangladesh]
                   3500TL DOSIMETRY                                              [CHENNAI]
                   3500TLD READER        [Kolkata, AHMEDABAD, Dhaka, LUCKNOW, Pondicherry]
                   3500TLD READER INSTR                             [LUCKNOW, Kanchipuram]
                   900E TUBE GM6.0CM2                                          [BANGALORE]
                   ALLOY ANALYZER 100G                     [Delhi, Indore, Chennai, Thane]
                   ALLOY ANALYZER 800               [Thane, DHAKA, MAHBOOB NAGAR, SONEPAT]
                   ASMIVSCU 2SINGLE RDM              [Kerala GIDC, Taluka : Bavla,Ahmedab]
                   AUTO SCRAP MONITOR                               [AHMEDABAD, BANGALORE]
                   BARGRAGRAPH COALBUNK  [BANGALORE, Mumbai, Aurangabad, Nabinagar, Sun...
                   BARGRAGRAPH M-SYS                                           [BANGALORE]
                   BELT SCALE            [Chittogarh, Ropar, Nellore, DANTEWADA, Bangal...
                   BELT WEIGHER                                  [VISAKHAPATNAM, Jamnagar]
                   BIN WEIGHING                                                    [KUTCH]
                   C-LEVEL INDICATOR                                           [BANGALORE]
                   CBOMNI1 ANALYZER      [KADAPA DIST, Chittorgrah, RAIPUR, TRICHY, KAD...
                   CBX ANALYZER          [JAIPUR, GULBARGA, JAMSHEDPUR, BALODA BAZAR, K...
                   CBX ANALYZER COAL                      [JAMSHEDPUR, BANGALORE, Chennai]
                   CCMNBR AMPLIFIER PCB                                            [Surat]
                   CEMENT ANALYZER                                              [Yavatmal]
                   CHARGER DXL                                                    [Mumbai]
                   CK101 PANEL                                                      [PUNE]
                   COAL SAMPLING SYS                                               [ANGUL]
                   COATING WEIGHT GAUGE                                        [Dhenkanal]
                   CONT C LVL                                        [Sundargarh, Jodhpur]
                   CONTAMINATION MONITR                            [Kalpakkam, DIST.THANE]
                   CQM ANALYZER                                  [Dwarka,Sector-11, HISAR]
                   CQM COAL QUALITY                                         [Yamuna Nagar]
                   CTRL PANEL 9105P                                           [Dist Mansa]
                   CTRLUT FHT6020                                                [Chennai]
...                                                                                    ...
Unknown            HPLC-U3000                                         [Gurgaon, BANGALORE]
                   High Perf LR&F                                   [HYDERABAD, Bangalore]
                   ICS6000                                            [BANGALORE, GURGAON]
                   LCMS-Altis                                           [MAHARASHTRA (27)]
                   LCMS-OT                                                          [PUNE]
                   LN2 Cryo                                                    [BANGALORE]
                   LSMS                                                        [BANGALORE]
                   MULTIGAS CALIBRATOR                                         [Goa Velha]
                   Micro Centrifuge                      [Srinagar, HAZARIBAGH, ALLAHABAD]
                   NANODROP LITE                                                  [KANPUR]
                   NANODROP ONEC                                                 [KOLKATA]
                   NOX ANALYZER                                                    [SIDHI]
                   OZONE ANALYZER                                              [Goa Velha]
                   Oven                                                           [Mumbai]
                   PM 10 ANALYZER                                                  [Delhi]
                   PROBE FHZ621                                                    [Surat]
                   RADEYE B20 H10 GAMMA                                         [KOLHAPUR]
                   RADEYE PX/WENDI N0                                              [Surat]
                   Remote Monitoring Sy                            [MALANPUR, DISTT BHIND]
                   SO2 ANALYZER                                                    [SIDHI]
                   SOFTWARE                                 [AGARTALA, THIRUVANANTHAPURAM]
                   Stirrer                                                      [Vadodara]
                   TRACE GC                                                         [Vapi]
                   Trace GC                                                   [Narsingarh]
                   TraceGC-AS                                                    [CHENNAI]
                   ULT Freezer                               [LUCKNOW, BANGALORE, Lucknow]
                   UV-VIS SPECTROPHOMTR                                         [Bhiwandi]
                   Value Enhanced LR&F                                            [Ladakh]
                   Water Purification                                          [BANGALORE]
                   iCAP6300-D                             [Bangalore, BANGALORE, VADODARA]

[820 rows x 3 columns]

In [516]:
mapped=cleaned_city[["Pincode","Division Name"]].merge(city_cleaning_df, left_on="Pincode", right_on="ship-to postal code",how="outer",indicator=True)
mapped

,Pincode,Division Name,ship-to city,ship-to postal code,_merge
0,515004.0,Anantapur Division,NaN,NaN,left_only
1,515004.0,Anantapur Division,NaN,NaN,left_only
2,515004.0,Anantapur Division,NaN,NaN,left_only
3,515004.0,Anantapur Division,NaN,NaN,left_only
4,515004.0,Anantapur Division,NaN,NaN,left_only
5,515004.0,Anantapur Division,NaN,NaN,left_only
6,515004.0,Anantapur Division,NaN,NaN,left_only
7,515004.0,Anantapur Division,NaN,NaN,left_only
8,515004.0,Anantapur Division,NaN,NaN,left_only
9,515004.0,Anantapur Division,NaN,NaN,left_only
10,515004.0,Anantapur Division,NaN,NaN,left_only
11,515731.0,Anantapur Division,NaN,NaN,left_only
12,515731.0,Anantapur Division,NaN,NaN,left_only
13,515731.0,Anantapur Division,NaN,NaN,left_only
14,515731.0,Anantapur Division,NaN,NaN,left_only
15,515731.0,Anantapur Division,NaN,NaN,left_only
16,515731.0,Anantapur Division,NaN,NaN,left_only
17,515731.0,Anantapur Division,NaN,NaN,left_only
18,515731.0,Anantapur Division,NaN,NaN,left_only
19,515731.0,Anantapur Division,NaN,NaN,left_only
20,515731.0,Anantapur Division,NaN,NaN,left_only
21,515731.0,Anantapur Division,NaN,NaN,left_only
22,515731.0,Anantapur Division,NaN,NaN,left_only
23,515731.0,Anantapur Division,NaN,NaN,left_only
24,515731.0,Anantapur Division,NaN,NaN,left_only
25,515731.0,Anantapur Division,NaN,NaN,left_only
26,515002.0,Anantapur Division,Anand,515002.0,both
27,515002.0,Anantapur Division,Anand,515002.0,both
28,515002.0,Anantapur Division,Anand,515002.0,both
29,515002.0,Anantapur Division,Anand,515002.0,both
...,...,...,...,...,...
438470,NaN,NaN,BANGALORE,580019.0,right_only
438471,NaN,NaN,Panchmahal,389351.0,right_only
438472,NaN,NaN,SRI LANKA,200.0,right_only
438473,NaN,NaN,GENOVA,16163.0,right_only
438474,NaN,NaN,Sangareddy,502330.0,right_only
438475,NaN,NaN,Sangareddy,502330.0,right_only
438476,NaN,NaN,HOSHIARPUR-DISTT,144203.0,right_only
438477,NaN,NaN,Hyderabad,500409.0,right_only
438478,NaN,NaN,Ranchi,853303.0,right_only
438479,NaN,NaN,Meenabakkam,600027.0,right_only
438480,NaN,NaN,Makwanpur,44100.0,right_only
438481,NaN,NaN,海口,570311.0,right_only
438482,NaN,NaN,Pune,411000.0,right_only
438483,NaN,NaN,Pune,411000.0,right_only
438484,NaN,NaN,COLUMBUS,43210.0,right_only
438485,NaN,NaN,Surat,395101.0,right_only
438486,NaN,NaN,Itanagar,79110.0,right_only
438487,NaN,NaN,GENOVA,16100.0,right_only
438488,NaN,NaN,Deogarh,814419.0,right_only
438489,NaN,NaN,Thimphu,11001.0,right_only
438490,NaN,NaN,CLERMONT FERRAND,63000.0,right_only
438491,NaN,NaN,Shanghai,200082.0,right_only
438492,NaN,NaN,VISHAKHAPATNAM,631173.0,right_only
438493,NaN,NaN,JAIPUR,302023.0,right_only
438494,NaN,NaN,Kochi,683509.0,right_only
438495,NaN,NaN,CHENNAI,600079.0,right_only
438496,NaN,NaN,Ahmedabad,380081.0,right_only
438497,NaN,NaN,Navi Mumbai,4000703.0,right_only
438498,NaN,NaN,BAGALKOTE,680051.0,right_only
438499,NaN,NaN,PHARR,78577.0,right_only

In [517]:
mapped["_merge"].value_counts()

both          303941
left_only     131676
right_only      2883
Name: _merge, dtype: int64

In [426]:
final_df=mapped[mapped["_merge"]=="both"]#.drop_duplicates()

In [509]:
mapped[mapped["_merge"]=="right_only"]["ship-to postal code"].nunique()

297

In [515]:
mapped[mapped["_merge"]=="left_only"]["_merge"].value_counts()

left_only     131676
right_only         0
both               0
Name: _merge, dtype: int64

In [442]:
final_df[["Division Name", "Pincode"]].value_counts()

Division Name                    Pincode
Secunderabad Division            500078.0    7040
Ahmedabad City Division          382210.0    5300
Pune Moffusil Division           412115.0    4238
Bengaluru South Division         560099.0    4029
Vadodara West Division           391440.0    4002
Valsad Division                  396035.0    3888
Gurgaon Division                 122001.0    3421
Bharuch Division                 392130.0    2608
Panchmahals Division             389350.0    2484
Thane Division                   421302.0    2254
Faridabad Division               121001.0    2216
Gandhinagar Division             382225.0    2214
                                 382213.0    2190
Udaipur Division                 313001.0    2025
Bhubaneswar Division             752050.0    2023
Jamnagar Division                361305.0    2014
Karnal Division                  132001.0    1938
South Presidency Division        743503.0    1890
Pune City East Division          411057.0    1800
Cuttack North Division           755026.0    1764
Dharamsala Division              176061.0    1632
Navi Mumbai Division             410208.0    1608
Secunderabad Division            500090.0    1512
Chengalpattu Division            603102.0    1500
Dehradun Division                247667.0    1450
Solan Division                   174101.0    1449
New Delhi South West Division    110067.0    1431
Lucknow Division                 226003.0    1428
Varanasi East Division           221005.0    1386
Delhi North Division             110007.0    1386
                                             ...
Ujjain Division                  456001.0       1
Ballari Division                 583118.0       1
Chandigarh Division              160043.0       1
Aurangabad Division              431010.0       1
Bengaluru East Division          560038.0       1
Srinagar Division                190007.0       1
Jaipur Moffusil Division         303121.0       1
                                 303329.0       1
Palghat Division                 678014.0       1
Secunderabad Division            500054.0       1
Palghar Division                 401608.0       1
Jalandhar Division               144011.0       1
Ahmedabad City Division          382443.0       1
Palghar Division                 401105.0       1
Mumbai City North West Division  400092.0       1
Gandhinagar Division             382729.0       1
Ottapalam Division               673122.0       1
Jammu Division                   180015.0       1
Ernakulam Division               682013.0       1
Nizamabad Division               503322.0       1
Jamnagar Division                361002.0       1
Mumbai City North West Division  400103.0       1
Gadag Division                   583233.0       1
Jodhpur Division                 342007.0       1
Thane Division                   421202.0       1
Kota Division                    324004.0       1
Koraput Division                 764048.0       1
Srinagar Division                190005.0       1
Cuttack City Division            753015.0       1
Shrirampur Division              413713.0       1
Length: 3342, dtype: int64

In [424]:
final_df.reset_index()

,index,Pincode,Division Name,ship-to city,ship-to postal code,_merge
0,26,515002.0,Anantapur Division,Anand,515002.0,both
1,46,515415.0,Anantapur Division,YADKI,515415.0,both
2,47,515415.0,Anantapur Division,Nellore,515415.0,both
3,49,515415.0,Anantapur Division,ANANTAPUR,515415.0,both
4,284,515001.0,Anantapur Division,ANANTAPUR,515001.0,both
5,285,515001.0,Anantapur Division,Ramnagar,515001.0,both
6,532,515411.0,Anantapur Division,ANANTPUR,515411.0,both
7,571,515408.0,Anantapur Division,ANANTHAPUR,515408.0,both
8,749,515721.0,Anantapur Division,ANANTAPUR,515721.0,both
9,798,515801.0,Anantapur Division,Guntakal,515801.0,both
10,821,515003.0,Anantapur Division,Anantapur,515003.0,both
11,1020,517127.0,Chittoor Division,Chittoor,517127.0,both
12,1100,517408.0,Chittoor Division,Chittoor,517408.0,both
13,1251,517325.0,Chittoor Division,Chatra,517325.0,both
14,1252,517325.0,Chittoor Division,MADANAPALLE,517325.0,both
15,1354,516003.0,Cuddapah Division,KADAPA,516003.0,both
16,1605,516162.0,Cuddapah Division,Kadapa,516162.0,both
17,1711,516002.0,Cuddapah Division,Kadpa,516002.0,both
18,1980,515134.0,Hindupur Division,Anantapur,515134.0,both
19,1985,515134.0,Hindupur Division,ANANTAPUR DISTRICT,515134.0,both
20,1999,515134.0,Hindupur Division,ANDHRA PRADESH,515134.0,both
21,2336,515341.0,Hindupur Division,Ananthapur,515341.0,both
22,2588,515201.0,Hindupur Division,Hindupura,515201.0,both
23,2589,515201.0,Hindupur Division,Hindupur,515201.0,both
24,2643,518301.0,Kurnool Division,"Kurnool,",518301.0,both
25,2694,518220.0,Kurnool Division,Kurnool,518220.0,both
26,2914,518004.0,Kurnool Division,KURNOOL (A.P),518004.0,both
27,2933,518508.0,Kurnool Division,KURNOOL,518508.0,both
28,2988,518002.0,Kurnool Division,AP,518002.0,both
29,2990,518002.0,Kurnool Division,Karnool,518002.0,both
...,...,...,...,...,...,...
5880,433335,711411.0,Howrah Division,Kolkata,711411.0,both
5881,433336,711411.0,Howrah Division,HOWRAH,711411.0,both
5882,433381,711202.0,Howrah Division,Howrah,711202.0,both
5883,433382,711202.0,Howrah Division,HOWRAH,711202.0,both
5884,433479,711101.0,Howrah Division,Kolkata,711101.0,both
5885,433480,711101.0,Howrah Division,HOWRAH,711101.0,both
5886,433495,711111.0,Howrah Division,HOWRAH,711111.0,both
5887,433508,721102.0,Midnapore Division,MIDNAPORE,721102.0,both
5888,433512,721102.0,Midnapore Division,DIST. PASCHIM,721102.0,both
5889,433931,721149.0,Midnapore Division,Kharagpur,721149.0,both
5890,434007,721301.0,Midnapore Division,MIDNAPORE,721301.0,both
5891,434008,721301.0,Midnapore Division,Kharagpur,721301.0,both
5892,434272,721129.0,Midnapore Division,Medenipur,721129.0,both
5893,434284,721147.0,Midnapore Division,Medinipur,721147.0,both
5894,434298,721101.0,Midnapore Division,MIDNAPORE,721101.0,both
5895,434355,721304.0,Midnapore Division,Kharagpur,721304.0,both
5896,434356,721304.0,Midnapore Division,KHARAGPUR,721304.0,both
5897,434384,721302.0,Midnapore Division,KHARAGPUR,721302.0,both
5898,434411,721302.0,Midnapore Division,Kharagpur,721302.0,both
5899,434772,723147.0,Purulia Division,Purulia,723147.0,both
5900,434951,723143.0,Purulia Division,West Bengal,723143.0,both
5901,434975,723104.0,Purulia Division,Purulia,723104.0,both
5902,435068,721635.0,Tamluk Division,BHUNIARAICHAK,721635.0,both
5903,435273,721645.0,Tamluk Division,MEDINIPUR,721645.0,both
5904,435321,721657.0,Tamluk Division,Haldia,721657.0,both
5905,435396,721602.0,Tamluk Division,Durgachak Haldia,721602.0,both
5906,435397,721602.0,Tamluk Division,Haldia,721602.0,both
5907,435398,721602.0,Tamluk Division,HALDIA,721602.0,both
5908,435402,721602.0,Tamluk Division,"HALDIA,DIST: MIDNAPORE (EAST),",721602.0,both
5909,435538,721606.0,Tamluk Division,HALDIA,721606.0,both

In [460]:
df["nans"]=np.nan

In [463]:
df.dropna(subset=["company code","nans"])

Empty DataFrame
Columns: [company code, equipment number, bill-to customer number, sold-to customer number, ship-to customer number, ship-to city, ship-to postal code, ship-to state, ship-to state name, industry segment, industry segment description, customer classification, customer class description, industry code, customer account type direct_asp, asp name, customer group code, focus account, last end user contact telephone ism2, last end user contact mobile ism2, last end user contact email ism, most used contact email ism2, most used email count ism, equipment fse number, equipment model, equipment model name, equipment material, equipment material description, equipment serial number, sort field, superior equipment, superior equipment description, product planner group, product planner group name, warranty type, sales office code, sales office name, equipment created on, equipment installed on, equipment system status, equipment user status, aag, aag description, warranty start date, warranty end date, equipment usage, order reason, equipment status, equipment shipped date, active contract header end date, reference start date, reference end date, extended warranty start date, extended warranty end date, active contract line value, active contract header value, contract number of years, last contract number, last contract line item, last contract header start date, last contract header end date, future contract line item, future contract header start date, future contract header end date, load_date, corrected division, nans]
Index: []

[0 rows x 67 columns]

In [467]:
###future contract
# 31791

# ###equipment serial
# 32


# ###32732
df.dropna(subset=["equipment serial number","future contract header end date"])

,company code,equipment number,bill-to customer number,sold-to customer number,ship-to customer number,ship-to city,ship-to postal code,ship-to state,ship-to state name,industry segment,...,last contract number,last contract line item,last contract header start date,last contract header end date,future contract line item,future contract header start date,future contract header end date,load_date,corrected division,nans
0,hello world,17279051,1146594.0,0001146594,0001146594,CHANDIGARH,160012,CD,Chandigarh,47.0,...,NaN,NaN,NaT,NaT,10.0,2022-12-06,2023-12-05,2022-06-16 01:38:48.728,CMD,NaN
1,2040,17194740,1665650.0,0001665650,0001665650,Hyderabad,501401,TG,Telangana,109.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-21,2024-09-20,2022-06-16 01:38:48.728,CMD,NaN
2,2040,17202899,1509501.0,0001509501,0001509501,Vadodara,391450,GU,Gujarat,11.0,...,NaN,NaN,NaT,NaT,10.0,2022-07-19,2026-07-18,2022-06-16 01:38:48.728,CMD,NaN
3,2040,16498250,1289243.0,0001289243,0001655354,Jammu,180004,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaT,NaT,30.0,2022-12-15,2025-12-14,2022-06-16 01:38:48.728,LSI,NaN
4,2040,17072866,1655736.0,0001655736,0001655736,PUNE,411007,MH,Maharashtra,19.0,...,NaN,NaN,NaT,NaT,10.0,2023-08-28,2025-08-27,2022-06-16 01:38:48.728,LSI,NaN
5,2040,16556865,NaN,0001464208,0001142136,Jammu,180001,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaT,NaT,20.0,2023-08-02,2026-08-01,2022-06-16 01:38:48.728,LSI,NaN
7,2040,16438610,1140935.0,0001140935,0001140935,HYDERABAD,500078,TG,Telangana,63.0,...,NaN,NaN,NaT,NaT,20.0,2023-09-14,2024-09-13,2022-06-16 01:38:48.728,LSI,NaN
8,2040,17271465,1657856.0,0001657856,0001657856,HISAR,125004,HR,Haryana,108.0,...,NaN,NaN,NaT,NaT,10.0,2022-10-30,2024-10-29,2022-06-16 01:38:48.728,CMD,NaN
9,2040,16644012,1289243.0,0001289243,0001641445,Srinagar,184140,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaT,NaT,10.0,2023-05-19,2026-05-18,2022-06-16 01:38:48.728,LSI,NaN
10,2040,16285984,1629806.0,0001629806,0001629806,"SriCity,",517646,AP,Andhra Pradesh,6.0,...,NaN,NaN,NaT,NaT,10.0,2022-08-05,2023-08-04,2022-06-16 01:38:48.728,LSI,NaN
11,2040,17266956,1288904.0,0001288904,0001288904,HYDERABAD,500049,TG,Telangana,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-12-19,2024-12-18,2022-06-16 01:38:48.728,CMD,NaN
12,2040,17070621,1137862.0,0001137862,0001137862,HYDERABAD,500007,TG,Telangana,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-07-16,2024-07-15,2022-06-16 01:38:48.728,CMD,NaN
13,2040,17266952,1288904.0,0001288904,0001288904,HYDERABAD,500049,TG,Telangana,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-12-19,2024-12-18,2022-06-16 01:38:48.728,CMD,NaN
14,2040,16550298,1598997.0,0001598997,0001210294,Kohima,797001,NG,Nagaland,27.0,...,NaN,NaN,NaT,NaT,20.0,2023-03-09,2024-03-08,2022-06-16 01:38:48.728,LSI,NaN
15,2040,17194746,1665650.0,0001665650,0001665650,Hyderabad,501401,TG,Telangana,109.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-30,2024-09-29,2022-06-16 01:38:48.728,CMD,NaN
17,2040,16634564,1478938.0,0001478938,0001638028,Raurkela,769005,OR,Orissa,111.0,...,NaN,NaN,NaT,NaT,40.0,2023-07-24,2024-07-23,2022-06-16 01:38:48.728,LSI,NaN
20,2040,17115466,1140073.0,0001140073,0001176026,Pune,411021,MH,Maharashtra,90.0,...,NaN,NaN,NaT,NaT,10.0,2024-07-20,2026-09-07,2022-06-16 01:38:48.728,LSI,NaN
21,2040,14241242,1159371.0,0001159371,0001159371,KAHALGAON,813214,BI,Bihar,31.0,...,40244085.0,40.0,2018-04-01,2020-03-31,10.0,2022-06-26,2024-06-25,2022-06-16 01:38:48.728,EPM,NaN
22,2040,17170861,1506796.0,0001506796,0001506796,TELANGANA,500037,TG,Telangana,88.0,...,NaN,NaN,NaT,NaT,10.0,2022-07-29,2024-07-28,2022-06-16 01:38:48.728,CMD,NaN
23,2040,16480231,1221643.0,0001221643,0001221643,JAIPUR,302004,RJ,Rajasthan,111.0,...,NaN,NaN,NaT,NaT,10.0,2023-09-04,2024-09-03,2022-06-16 01:38:48.728,LSI,NaN
24,2040,17641723,1141280.0,0001141280,0001141280,Bangalore,560058,KA,Karnataka,6.0,...,NaN,NaN,NaT,NaT,10.0,2023-08-13,2025-08-12,2022-06-16 01:38:48.728,CMD,NaN
25,2040,17159153,1661387.0,0001661387,0001661387,Tuticorin,628501,TN,Tamil Nadu,108.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-16,2024-09-15,2022-06-16 01:38:48.728,CMD,NaN
26,2040,15038954,1500896.0,0001500896,0001500896,Chanderia,312021,RJ,Rajasthan,111.0,...,40338834.0,10.0,2020-07-21,2021-07-20,10.0,2022-09-01,2023-08-31,2022-06-16 01:38:48.728,EPM,NaN
27,2040,17054405,1589541.0,0001589541,0001589541,HYDERABAD,500078,TG,Telangana,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-07-27,2024-07-26,2022-06-16 01:38:48.728,CMD,NaN
28,2040,17055240,1506796.0,0001506796,0001506796,TELANGANA,500037,TG,Telangana,88.0,...,NaN,NaN,NaT,NaT,10.0,2022-08-05,2023-11-04,2022-06-16 01:38:48.728,CMD,NaN
29,2040,13419863,1138734.0,0001138734,0001138734,MUMBAI,400079,MH,Maharashtra,90.0,...,40357809.0,30.0,2021-10-01,2022-03-31,30.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,NaN
30,2040,16327544,1500896.0,0001500896,0001500896,Chanderia,312021,RJ,Rajasthan,111.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-01,2023-08-31,2022-06-16 01:38:48.728,EPM,NaN
31,2040,17126419,1509501.0,0001509501,0001509501,Vadodara,391450,GU,Gujarat,11.0,...,NaN,NaN,NaT,NaT,10.0,2022-07-15,2026-07-14,2022-06-16 01:38:48.728,CMD,NaN
33,2040,16631501,1652402.0,0001652402,0001652402,Vadodara,391776,GU,Gujarat,88.0,...,NaN,NaN,NaT,NaT,10.0,2024-04-12,2026-04-11,2022-06-16 01:38:48.728,LSI,NaN
34,2040,16590763,1221399.0,0001221399,0001643056,Delhi,110029,DE,Delhi,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-08-30,2025-08-29,2022-06-16 01:38:48.728,LSI,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52369,2040,16550288,1640287.0,0001640287,0001642135,Ulhas Nagar,421101,MH,Maharashtra,29.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-18,2025-09-17,2022-06-16 01:38:48.728,LSI,NaN
52384,2040,17156917,1440110.0,0001440110,0001141374,CHANDIGARH,160012,CD,Chandigarh,111.0,...,NaN,NaN,NaT,NaT,10.0,2022-07-23,2024-07-22,2022-06-16 01:38:48.728,LSI,NaN
52477,2040,17018220,1332225.0,0001332225,0001661200,GURGAON,122001,HR,Haryana,88.0,...,NaN,NaN,NaT,NaT,10.0,2023-07-28,2025-07-27,2022-06-16 01:38:48.728,LSI,NaN
52580,2040,17184815,1628463.0,0001628463,0001146594,CHANDIGARH,160012,CD,Chandigarh,27.0,...,NaN,NaN,NaT,NaT,10.0,2023-10-26,2024-10-25,2022-06-16 01:38:48.728,LSI,NaN
52611,2040,17031087,1501451.0,0001501451,0001501451,Nalgonda,508252,TG,Telangana,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-08-01,2023-07-31,2022-06-16 01:38:48.728,CMD,NaN
52629,2040,16564118,1462602.0,0001462602,0001462602,Jabalpur,482003,MP,Madhya Pradesh,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-10-29,2025-10-28,2022-06-16 01:38:48.728,LSI,NaN
52766,2040,15806900,1625820.0,0001625820,0001625820,LUCKNOW,226010,UP,Uttar Pradesh,47.0,...,NaN,NaN,NaT,NaT,10.0,2022-08-19,2025-08-18,2022-06-16 01:38:48.728,LSI,NaN
52828,2040,16460493,1321944.0,0001321944,0001321944,MUMBAI,400004,MH,Maharashtra,88.0,...,NaN,NaN,NaT,NaT,10.0,2023-07-29,2025-07-28,2022-06-16 01:38:48.728,LSI,NaN
52844,2040,16509634,1221399.0,0001221399,0001645744,"Banda,",210001,UP,Uttar Pradesh,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-29,2023-09-28,2022-06-16 01:38:48.728,LSI,NaN
52879,2040,17158523,1288645.0,0001288645,0001667890,KOCHI,682508,KE,Kerala,27.0,...,NaN,NaN,NaT,NaT,10.0,2022-10-12,2024-10-11,2022-06-16 01:38:48.728,LSI,NaN
53001,2040,16561031,1289243.0,0001289243,0001641444,Srinagar,193101,JK,Jammu and Kashmir,27.0,...,NaN,NaN,NaT,NaT,10.0,2022-08-31,2025-08-30,2022-06-16 01:38:48.728,LSI,NaN
53005,2040,17090009,1226700.0,0001226700,0001190786,NOIDA,201301,UP,Uttar Pradesh,111.0,...,NaN,NaN,NaT,NaT,10.0,2022-08-27,2023-08-26,2022-06-16 01:38:48.728,LSI,NaN
53035,2040,17648852,1526133.0,0001526133,0001526133,Palghar,401506,MH,Maharashtra,90.0,...,NaN,NaN,NaT,NaT,10.0,2023-08-01,2024-07-31,2022-06-16 01:38:48.728,CMD,NaN
53068,2040,16937363,1289100.0,0001289100,0001655362,Jamshedpur,831001,JH,Jharkhand,31.0,...,NaN,NaN,NaT,NaT,10.0,2023-07-20,2026-07-19,2022-06-16 01:38:48.728,LSI,NaN
53089,2040,16795746,1652413.0,0001652413,0001652150,Bangalore,560052,KA,Karnataka,74.0,...,NaN,NaN,NaT,NaT,10.0,2023-04-05,2026-04-04,2022-06-16 01:38:48.728,LSI,NaN
53179,2040,16739028,1612661.0,0001612661,0001612661,Kakinada,533001,AP,Andhra Pradesh,73.0,...,NaN,NaN,NaT,NaT,10.0,2023-01-07,2024-01-06,2022-06-16 01:38:48.728,LSI,NaN
53227,2040,16550294,1640287.0,0001640287,0001642134,Bhiwandi,421302,MH,Maharashtra,29.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-03,2025-09-02,2022-06-16 01:38:48.728,LSI,NaN
53230,2040,17089927,1559196.0,0001559196,0001668507,BARAGARH,768028,OR,Orissa,27.0,...,NaN,NaN,NaT,NaT,10.0,2022-10-30,2024-10-29,2022-06-16 01:38:48.728,LSI,NaN
53305,2040,17098825,1598997.0,0001598997,0001662592,Kochi,682004,KE,Kerala,27.0,...,NaN,NaN,NaT,NaT,10.0,2023-09-24,2024-09-23,2022-06-16 01:38:48.728,LSI,NaN
53519,2040,17197385,1580244.0,0001580244,0001661026,Madurai,625007,TN,Tamil Nadu,27.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-09,2023-09-08,2022-06-16 01:38:48.728,CMD,NaN
53690,2040,16395464,1208051.0,0001208051,0001208051,DELHI,110085,DE,Delhi,88.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-14,2023-09-13,2022-06-16 01:38:48.728,LSI,NaN
53918,2040,16460491,1321944.0,0001321944,0001321944,MUMBAI,400004,MH,Maharashtra,88.0,...,NaN,NaN,NaT,NaT,10.0,2023-08-05,2025-08-04,2022-06-16 01:38:48.728,LSI,NaN
53923,2040,17056707,1221399.0,0001221399,0001662979,Bijnor,246701,UP,Uttar Pradesh,90.0,...,NaN,NaN,NaT,NaT,10.0,2023-08-12,2024-08-11,2022-06-16 01:38:48.728,LSI,NaN
54008,2040,16759969,1653558.0,0001653558,0001653558,Agartala,799006,TR,Tripura,111.0,...,NaN,NaN,NaT,NaT,10.0,2023-01-15,2028-01-14,2022-06-16 01:38:48.728,CMD,NaN
54068,2040,17211683,1440110.0,0001440110,0001647230,Ladakh,194103,NaN,NaN,111.0,...,NaN,NaN,NaT,NaT,10.0,2022-12-10,2026-12-09,2022-06-16 01:38:48.728,LSI,NaN
54144,2040,16074214,1221399.0,0001221399,0001639122,Varanasi,231001,UP,Uttar Pradesh,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-09-27,2023-09-26,2022-06-16 01:38:48.728,LSI,NaN
54242,2040,16568721,1652411.0,0001652411,0001652411,"Ranchi,",834010,JH,Jharkhand,29.0,...,NaN,NaN,NaT,NaT,10.0,2022-12-10,2027-12-09,2022-06-16 01:38:48.728,CMD,NaN
54397,2040,16724236,1311738.0,0001311738,0001648810,Jaipur,303108,RJ,Rajasthan,88.0,...,NaN,NaN,NaT,NaT,10.0,2023-01-16,2024-01-15,2022-06-16 01:38:48.728,LSI,NaN
54531,2040,13419856,1137874.0,0001137874,0001137874,PATALGANGA,410207,MH,Maharashtra,90.0,...,40370868.0,10.0,2021-10-01,2022-03-31,10.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,NaN
54558,2040,16549601,1141341.0,0001141341,0001141341,NEW DELHI,110067,DE,Delhi,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-10-24,2025-10-23,2022-06-16 01:38:48.728,LSI,NaN

In [470]:
df["nans"]=np.arange(32732)

In [473]:
###nans number 820
###17111776
df["nans"]=df["nans"].replace(to_replace=820,value=33000)

In [477]:
df.sort_values(by="nans", ascending=False, inplace=True)

In [478]:
df.drop_duplicates(subset="ship-to city")

,company code,equipment number,bill-to customer number,sold-to customer number,ship-to customer number,ship-to city,ship-to postal code,ship-to state,ship-to state name,industry segment,...,last contract number,last contract line item,last contract header start date,last contract header end date,future contract line item,future contract header start date,future contract header end date,load_date,corrected division,nans
1208,2040,17111776,1600497.0,0001600497,0001600497,Mumbai,400093,MH,Maharashtra,111.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,33000
54559,2040,16616453,1289273.0,0001289273,0001289273,GURGAON,122050,HR,Haryana,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32731
54558,2040,16549601,1141341.0,0001141341,0001141341,NEW DELHI,110067,DE,Delhi,90.0,...,NaN,NaN,NaT,NaT,10.0,2022-10-24,2025-10-23,2022-06-16 01:38:48.728,LSI,32730
54556,2040,17474156,1676105.0,0001676105,0001676105,Vadodara,390021,GU,Gujarat,111.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32729
54555,2040,16596803,1633219.0,0001633219,0001633219,Ahmedabad,382213,GU,Gujarat,86.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32728
54553,2040,16192628,1543368.0,0001543368,0001543368,Jammu,181143,JK,Jammu and Kashmir,47.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32727
54551,2040,14366401,1138829.0,0001138829,0001138829,NAGAPATTINAM,611002,TN,Tamil Nadu,11.0,...,40134357.0,30.0,2013-12-02,2018-12-01,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,32726
54550,2040,12067819,1139911.0,0001139911,0001139911,KANPUR,208012,UP,Uttar Pradesh,90.0,...,40083773.0,10.0,2011-07-01,2012-06-30,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,32725
54549,2040,15123843,1566819.0,0001566819,0001566819,Chennai,600058,TN,Tamil Nadu,92.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32724
54548,2040,17005743,1141204.0,0001141204,0001141204,Bangalore,560029,KA,Karnataka,88.0,...,40354727.0,10.0,2021-02-05,2022-02-04,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32723
54547,2040,17278258,1250700.0,0001250700,0001250700,NIMBAHERA,312601,RJ,Rajasthan,11.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,32722
54546,2040,17196936,1456078.0,0001456078,0001456078,Pune,411011,MH,Maharashtra,88.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32721
54545,2040,16300531,1332016.0,0001332016,0001332016,MORAIYA,382213,GU,Gujarat,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32720
54543,2040,14210460,1146817.0,0001146817,0001146817,Imphal,795004,MN,Manipur,47.0,...,40202685.0,10.0,2017-03-15,2019-03-14,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32718
54540,2040,15600615,1300205.0,0001300205,0001300205,PANCHWATI PUNE,411008,MH,Maharashtra,8.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32716
54537,2040,14894283,1242918.0,0001242918,0001242918,PUNE,411021,MH,Maharashtra,90.0,...,40363524.0,20.0,2021-04-01,2022-03-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32715
54535,2040,13965054,1030068.0,0001030068,0001404808,"Kalyani Nagar, PUNE",411 014,NaN,NaN,63.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,32714
54534,2040,14775067,1554215.0,0001554215,0001554215,Srinagar,190015,JK,Jammu and Kashmir,47.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32713
54533,2040,16530345,1547016.0,0001547016,0001547016,Nagpur,441108,MH,Maharashtra,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32712
54532,2040,13985248,1137859.0,0001137859,0001137859,GUWAHATI,781039,AS,Assam,47.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32711
54531,2040,13419856,1137874.0,0001137874,0001137874,PATALGANGA,410207,MH,Maharashtra,90.0,...,40370868.0,10.0,2021-10-01,2022-03-31,10.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,32710
54528,2040,16165109,1332153.0,0001332153,0001332153,INDRAD,382715,GU,Gujarat,90.0,...,40367221.0,10.0,2020-12-27,2021-12-26,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32709
54527,2040,12095127,1139820.0,0001139820,0001139820,JORHAT,785704,AS,Assam,31.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32708
54526,2040,14564413,1141331.0,0001141331,0001141331,DELHI,110003,DE,Delhi,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32707
54524,2040,14376830,1147989.0,0001147989,0001147989,Medak,502307,TG,Telangana,8.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32706
54522,2040,16446049,1220819.0,0001220819,0001612077,Navi Mumbai,400708,MH,Maharashtra,8.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32705
54521,2040,16324675,1139842.0,0001139842,0001139842,VADODARA,390001,GU,Gujarat,11.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,32704
54520,2040,16049271,169918.0,0000169918,0000169918,New Delhi,110067,DE,Delhi,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32703
54515,2040,10471480,1141046.0,0001141046,0001141046,NAVI MUMBAI,400708,MH,Maharashtra,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,32702
54512,2040,12098862,1560559.0,0001560559,0001560559,Karwar,581400,KA,Karnataka,14.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CAD,32700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499,2040,10783418,1389426.0,0001389426,0001389426,Vakalapudi,533005,AP,Andhra Pradesh,111.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1577
2470,2040,12058838,1203907.0,0001203907,0001203907,GANDHIDHAM(KUTCH),370201,GU,Gujarat,27.0,...,40083370.0,10.0,2010-08-04,2011-08-03,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,1558
2418,2040,15740591,1598152.0,0001598152,0001598152,VELUR NAMAKKAL,637206,TN,Tamil Nadu,111.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1529
2369,2040,15422555,1570845.0,0001570845,0001570845,MEDINIPUR,721645,WB,West Bengal,58.0,...,40338107.0,10.0,2020-09-24,2021-09-23,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1501
2333,2040,17548376,1635166.0,0001635166,0001485415,Jagadhri,135003,HR,Haryana,27.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1482
2190,2040,10182650,1032392.0,0001032392,0000131106,GREEN BAY,54302,WI,Wisconsin,31.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,1404
2047,2040,10852045,1064257.0,0001028557,0001065938,DHARMSALA,176215,NaN,NaN,27.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,1311
1978,2040,17524597,1581423.0,0001581423,0001581423,UDAIPUR (RAJASTHAN),313001,RJ,Rajasthan,11.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MSD,1268
1974,2040,14817224,1332181.0,0001332181,0001332181,Moraiya,382110,GU,Gujarat,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,1265
1931,2040,14103182,1434292.0,0001434292,0001434292,"Sidhpur, Dist. Patan",384151,GU,Gujarat,6.0,...,40349952.0,10.0,2021-02-24,2022-02-23,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1234
1891,2040,16972864,1558824.0,0001558824,0001558824,MAHBUBNAGAR,509301,TG,Telangana,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,1211
1535,2040,17230818,1363455.0,0001363455,0001688663,Harur,636903,TN,Tamil Nadu,6.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,998
1513,2040,17315709,1559196.0,0001559196,0001675953,Sonarpur,743330,WB,West Bengal,27.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,985
1473,2040,13852919,1138384.0,0001138384,0001493957,"Rabale, Navi Mumbai",400701,MH,Maharashtra,6.0,...,40340184.0,10.0,2020-11-01,2021-07-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,967
1215,2040,11341854,1104340.0,0001104340,0001104340,DIST. JUNAGADH,362715,GU,Gujarat,11.0,...,40339114.0,10.0,2020-09-02,2021-09-01,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,825
1193,2040,17130412,1471125.0,0001471125,0001663011,"Nanded,",431601,MH,Maharashtra,90.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,809
1138,2040,10455817,1320565.0,0001320565,0001320565,BASAR,791101,ARP,Arunachal Pradesh,47.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,781
919,2040,15702324,1560576.0,0001560576,0001560576,"Kachar, Assam",788015,AS,Assam,30.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,651
912,2040,11027397,1215901.0,0001215901,0001215901,MIRZAPUR,231311,UP,Uttar Pradesh,111.0,...,40326292.0,20.0,2020-03-01,2022-02-28,NaN,NaT,NaT,2022-06-16 01:38:48.728,MSD,647
809,2040,15677942,1067042.0,0001067042,0001067042,Sarigam,396155,GU,Gujarat,NaN,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,586
761,2040,11698612,1153455.0,0001153757,0001153757,NEWANSHAHAR,144533,PU,Punjab,90.0,...,40148354.0,10.0,2014-11-01,2015-10-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,552
737,2040,14210181,1288354.0,0001288354,0001288354,SAMALKHA,132101,HR,Haryana,6.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,538
686,2040,12799533,1321301.0,0001321301,0001321301,PHAGWARA,144401,PU,Punjab,111.0,...,40356074.0,10.0,2021-04-28,2022-04-27,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,510
652,2040,12300827,1610936.0,0001610936,0001610936,Godhra,389001,GU,Gujarat,75.0,...,40359342.0,10.0,2021-04-01,2022-03-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,493
646,2040,10475571,1260306.0,0001260306,0001260306,"AMBERNATH,THANE",400602,MH,Maharashtra,90.0,...,40188606.0,10.0,2016-05-01,2017-04-30,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,489
581,2040,14141057,1628669.0,0001628669,0001628669,Thimphu,1071,BU,BUMTHANG,29.0,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,449
477,2040,17279880,1668279.0,0001668279,0001668279,Boralesgamuwa,10290,NaN,NaN,NaN,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,382
369,2040,16556985,1598997.0,0001598997,0001648045,Pawapuri,803115,BI,Bihar,27.0,...,NaN,NaN,NaT,NaT,30.0,2023-03-16,2024-03-15,2022-06-16 01:38:48.728,LSI,312
354,2040,13988986,1616296.0,0001616296,0001616296,East Sikkim,737133,SK,Sikkim,90.0,...,40359417.0,10.0,2021-10-01,2022-03-31,10.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,301
313,2040,13419592,1288927.0,0001288927,0001288927,"PITHAMPUR, DHAR",454775,MP,Madhya Pradesh,90.0,...,40362065.0,10.0,2021-10-01,2022-03-31,10.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,270

In [449]:
##index 712
##equip no 13419460
##522
df["nans"]=df["nans"].replace(to_replace=522, value=33000)

In [455]:
df.sort_values(by='nans',ascending=False).drop_duplicates(subset="ship-to city").reset_index()

,index,company code,equipment number,bill-to customer number,sold-to customer number,ship-to customer number,ship-to city,ship-to postal code,ship-to state,ship-to state name,...,last contract number,last contract line item,last contract header start date,last contract header end date,future contract line item,future contract header start date,future contract header end date,load_date,corrected division,nans
0,712,2040,13419460,1574471.0,0001574471,0001574471,Mumbai,400093,MH,Maharashtra,...,40354782.0,10.0,2021-03-01,2022-02-28,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,33000
1,54559,2040,16616453,1289273.0,0001289273,0001289273,GURGAON,122050,HR,Haryana,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32731
2,54558,2040,16549601,1141341.0,0001141341,0001141341,NEW DELHI,110067,DE,Delhi,...,NaN,NaN,NaT,NaT,10.0,2022-10-24,2025-10-23,2022-06-16 01:38:48.728,LSI,32730
3,54556,2040,17474156,1676105.0,0001676105,0001676105,Vadodara,390021,GU,Gujarat,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32729
4,54555,2040,16596803,1633219.0,0001633219,0001633219,Ahmedabad,382213,GU,Gujarat,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32728
5,54553,2040,16192628,1543368.0,0001543368,0001543368,Jammu,181143,JK,Jammu and Kashmir,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32727
6,54551,2040,14366401,1138829.0,0001138829,0001138829,NAGAPATTINAM,611002,TN,Tamil Nadu,...,40134357.0,30.0,2013-12-02,2018-12-01,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,32726
7,54550,2040,12067819,1139911.0,0001139911,0001139911,KANPUR,208012,UP,Uttar Pradesh,...,40083773.0,10.0,2011-07-01,2012-06-30,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,32725
8,54549,2040,15123843,1566819.0,0001566819,0001566819,Chennai,600058,TN,Tamil Nadu,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32724
9,54548,2040,17005743,1141204.0,0001141204,0001141204,Bangalore,560029,KA,Karnataka,...,40354727.0,10.0,2021-02-05,2022-02-04,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32723
10,54547,2040,17278258,1250700.0,0001250700,0001250700,NIMBAHERA,312601,RJ,Rajasthan,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,32722
11,54546,2040,17196936,1456078.0,0001456078,0001456078,Pune,411011,MH,Maharashtra,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32721
12,54545,2040,16300531,1332016.0,0001332016,0001332016,MORAIYA,382213,GU,Gujarat,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32720
13,54543,2040,14210460,1146817.0,0001146817,0001146817,Imphal,795004,MN,Manipur,...,40202685.0,10.0,2017-03-15,2019-03-14,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32718
14,54540,2040,15600615,1300205.0,0001300205,0001300205,PANCHWATI PUNE,411008,MH,Maharashtra,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32716
15,54537,2040,14894283,1242918.0,0001242918,0001242918,PUNE,411021,MH,Maharashtra,...,40363524.0,20.0,2021-04-01,2022-03-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32715
16,54535,2040,13965054,1030068.0,0001030068,0001404808,"Kalyani Nagar, PUNE",411 014,NaN,NaN,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,32714
17,54534,2040,14775067,1554215.0,0001554215,0001554215,Srinagar,190015,JK,Jammu and Kashmir,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32713
18,54533,2040,16530345,1547016.0,0001547016,0001547016,Nagpur,441108,MH,Maharashtra,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32712
19,54532,2040,13985248,1137859.0,0001137859,0001137859,GUWAHATI,781039,AS,Assam,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32711
20,54531,2040,13419856,1137874.0,0001137874,0001137874,PATALGANGA,410207,MH,Maharashtra,...,40370868.0,10.0,2021-10-01,2022-03-31,10.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,32710
21,54528,2040,16165109,1332153.0,0001332153,0001332153,INDRAD,382715,GU,Gujarat,...,40367221.0,10.0,2020-12-27,2021-12-26,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32709
22,54527,2040,12095127,1139820.0,0001139820,0001139820,JORHAT,785704,AS,Assam,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,32708
23,54526,2040,14564413,1141331.0,0001141331,0001141331,DELHI,110003,DE,Delhi,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32707
24,54524,2040,14376830,1147989.0,0001147989,0001147989,Medak,502307,TG,Telangana,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32706
25,54522,2040,16446049,1220819.0,0001220819,0001612077,Navi Mumbai,400708,MH,Maharashtra,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32705
26,54521,2040,16324675,1139842.0,0001139842,0001139842,VADODARA,390001,GU,Gujarat,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,32704
27,54520,2040,16049271,169918.0,0000169918,0000169918,New Delhi,110067,DE,Delhi,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,32703
28,54515,2040,10471480,1141046.0,0001141046,0001141046,NAVI MUMBAI,400708,MH,Maharashtra,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,32702
29,54512,2040,12098862,1560559.0,0001560559,0001560559,Karwar,581400,KA,Karnataka,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CAD,32700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2162,2499,2040,10783418,1389426.0,0001389426,0001389426,Vakalapudi,533005,AP,Andhra Pradesh,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1577
2163,2470,2040,12058838,1203907.0,0001203907,0001203907,GANDHIDHAM(KUTCH),370201,GU,Gujarat,...,40083370.0,10.0,2010-08-04,2011-08-03,NaN,NaT,NaT,2022-06-16 01:38:48.728,EPM,1558
2164,2418,2040,15740591,1598152.0,0001598152,0001598152,VELUR NAMAKKAL,637206,TN,Tamil Nadu,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1529
2165,2369,2040,15422555,1570845.0,0001570845,0001570845,MEDINIPUR,721645,WB,West Bengal,...,40338107.0,10.0,2020-09-24,2021-09-23,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1501
2166,2333,2040,17548376,1635166.0,0001635166,0001485415,Jagadhri,135003,HR,Haryana,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1482
2167,2190,2040,10182650,1032392.0,0001032392,0000131106,GREEN BAY,54302,WI,Wisconsin,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,1404
2168,2047,2040,10852045,1064257.0,0001028557,0001065938,DHARMSALA,176215,NaN,NaN,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,1311
2169,1978,2040,17524597,1581423.0,0001581423,0001581423,UDAIPUR (RAJASTHAN),313001,RJ,Rajasthan,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MSD,1268
2170,1974,2040,14817224,1332181.0,0001332181,0001332181,Moraiya,382110,GU,Gujarat,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,1265
2171,1931,2040,14103182,1434292.0,0001434292,0001434292,"Sidhpur, Dist. Patan",384151,GU,Gujarat,...,40349952.0,10.0,2021-02-24,2022-02-23,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,1234
2172,1891,2040,16972864,1558824.0,0001558824,0001558824,MAHBUBNAGAR,509301,TG,Telangana,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,1211
2173,1535,2040,17230818,1363455.0,0001363455,0001688663,Harur,636903,TN,Tamil Nadu,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,998
2174,1513,2040,17315709,1559196.0,0001559196,0001675953,Sonarpur,743330,WB,West Bengal,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,985
2175,1473,2040,13852919,1138384.0,0001138384,0001493957,"Rabale, Navi Mumbai",400701,MH,Maharashtra,...,40340184.0,10.0,2020-11-01,2021-07-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,967
2176,1215,2040,11341854,1104340.0,0001104340,0001104340,DIST. JUNAGADH,362715,GU,Gujarat,...,40339114.0,10.0,2020-09-02,2021-09-01,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,825
2177,1193,2040,17130412,1471125.0,0001471125,0001663011,"Nanded,",431601,MH,Maharashtra,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,809
2178,1138,2040,10455817,1320565.0,0001320565,0001320565,BASAR,791101,ARP,Arunachal Pradesh,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,781
2179,919,2040,15702324,1560576.0,0001560576,0001560576,"Kachar, Assam",788015,AS,Assam,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,651
2180,912,2040,11027397,1215901.0,0001215901,0001215901,MIRZAPUR,231311,UP,Uttar Pradesh,...,40326292.0,20.0,2020-03-01,2022-02-28,NaN,NaT,NaT,2022-06-16 01:38:48.728,MSD,647
2181,809,2040,15677942,1067042.0,0001067042,0001067042,Sarigam,396155,GU,Gujarat,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,586
2182,761,2040,11698612,1153455.0,0001153757,0001153757,NEWANSHAHAR,144533,PU,Punjab,...,40148354.0,10.0,2014-11-01,2015-10-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,552
2183,737,2040,14210181,1288354.0,0001288354,0001288354,SAMALKHA,132101,HR,Haryana,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,538
2184,686,2040,12799533,1321301.0,0001321301,0001321301,PHAGWARA,144401,PU,Punjab,...,40356074.0,10.0,2021-04-28,2022-04-27,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,510
2185,652,2040,12300827,1610936.0,0001610936,0001610936,Godhra,389001,GU,Gujarat,...,40359342.0,10.0,2021-04-01,2022-03-31,NaN,NaT,NaT,2022-06-16 01:38:48.728,LSI,493
2186,646,2040,10475571,1260306.0,0001260306,0001260306,"AMBERNATH,THANE",400602,MH,Maharashtra,...,40188606.0,10.0,2016-05-01,2017-04-30,NaN,NaT,NaT,2022-06-16 01:38:48.728,CMD,489
2187,581,2040,14141057,1628669.0,0001628669,0001628669,Thimphu,1071,BU,BUMTHANG,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,449
2188,477,2040,17279880,1668279.0,0001668279,0001668279,Boralesgamuwa,10290,NaN,NaN,...,NaN,NaN,NaT,NaT,NaN,NaT,NaT,2022-06-16 01:38:48.728,MOL,382
2189,369,2040,16556985,1598997.0,0001598997,0001648045,Pawapuri,803115,BI,Bihar,...,NaN,NaN,NaT,NaT,30.0,2023-03-16,2024-03-15,2022-06-16 01:38:48.728,LSI,312
2190,354,2040,13988986,1616296.0,0001616296,0001616296,East Sikkim,737133,SK,Sikkim,...,40359417.0,10.0,2021-10-01,2022-03-31,10.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,301
2191,313,2040,13419592,1288927.0,0001288927,0001288927,"PITHAMPUR, DHAR",454775,MP,Madhya Pradesh,...,40362065.0,10.0,2021-10-01,2022-03-31,10.0,2022-10-01,2023-03-31,2022-06-16 01:38:48.728,CMD,270

In [284]:
df["USD Dollars"]=np.random.randint(1000,100000,size=len(df))

In [285]:
df.dropna(subset="ship-to postal code",inplace=True)
df["ship-to postal code"]=pd.to_numeric(df["ship-to postal code"],errors="coerce")
merge=cleaned_city[["Pincode","Division Name"]].merge(df, left_on="Pincode", right_on="ship-to postal code",how="outer",indicator=True)

In [286]:
df=merge[merge["_merge"]=="both"].drop_duplicates()

In [288]:
np.round(df[["USD Dollars","Ageing of the product (in years)"]].groupby([df["corrected division"], df["equipment model name"]]).mean())

                                         USD Dollars  \
corrected division equipment model name
CAD                3500TLD READER            23632.0
                   ALLOY ANALYZER 100G       47434.0
                   ALLOY ANALYZER 800        54813.0
                   AUTO SCRAP MONITOR        98332.0
                   BELT SCALE                55326.0
                   BELT WEIGHER              60392.0
                   CBX ANALYZER              35596.0
                   COAL SAMPLING SYS         55945.0
                   COATING WEIGHT GAUGE      72837.0
                   CQM ANALYZER              69732.0
                   DOSIMTR GAMMA GREY        55890.0
                   EPD BETAGAMMA GREY        54038.0
                   EPD BLACK                 21481.0
                   EPD YELLOW                49760.0
                   IPLUS WEBTHICKNESS        93190.0
                   LE COTNG WEIGH GAUGE      36104.0
                   METAL DETECTORATEX22      56579.0
                   MICROTECH 9100F           11598.0
                   MINIAMP                   51186.0
                   ORETRONICSIII TMD         49544.0
                   RADEYEB20 a FLTR RJT      20609.0
                   RADIOMETRIE RM200E-M      71648.0
                   RM100 METALTHICKNESS      25720.0
                   RM120 EM STRIP            97864.0
                   RM130 METALTHICKNESS      88220.0
                   RM200 METALTHICKNESS      62123.0
                   RM200EG THICKNESSSYS      55367.0
                   RM200EM METALTHIKNSS      51571.0
                   RM210 METALTHICKNESS      56687.0
                   RM215 METALTHICKNESS      28286.0
...                                              ...
Unknown            HC ANALYZER               20518.0
                   HPLC-Colmn                62835.0
                   HPLC-P4000                49327.0
                   HPLC-Pump                 73916.0
                   HPLC-U3000                25544.0
                   High Perf LR&F            45712.0
                   ICS6000                   59682.0
                   LCMS-Altis                26895.0
                   LCMS-OT                   63752.0
                   LN2 Cryo                   9320.0
                   LSMS                      28636.0
                   MULTIGAS CALIBRATOR       32451.0
                   Micro Centrifuge          46826.0
                   NANODROP LITE             11183.0
                   NANODROP ONEC             85169.0
                   NOX ANALYZER              10473.0
                   OZONE ANALYZER            72739.0
                   Oven                      74839.0
                   PM 10 ANALYZER             7991.0
                   Remote Monitoring Sy      61352.0
                   SO2 ANALYZER              46078.0
                   SOFTWARE                  74539.0
                   Stirrer                   56723.0
                   TRACE GC                  10106.0
                   Trace GC                  86773.0
                   TraceGC-AS                40630.0
                   ULT Freezer               41485.0
                   UV-VIS SPECTROPHOMTR      35223.0
                   Value Enhanced LR&F       66421.0
                   iCAP6300-D                26635.0

                                         Ageing of the product (in years)
corrected division equipment model name
CAD                3500TLD READER                                     2.0
                   ALLOY ANALYZER 100G                                5.0
                   ALLOY ANALYZER 800                                 6.0
                   AUTO SCRAP MONITOR                                 2.0
                   BELT SCALE                                         3.0
                   BELT WEIGHER                                       3.0
                   CBX ANALYZER                                       9.0
                   COAL SAMPLING SYS                                  2.0
                   COATING WEIGHT GAUGE                               2.0
                   CQM ANALYZER                                      15.0
                   DOSIMTR GAMMA GREY                                12.0
                   EPD BETAGAMMA GREY                                11.0
                   EPD BLACK                                          3.0
                   EPD YELLOW                                        11.0
                   IPLUS WEBTHICKNESS                                 1.0
                   LE COTNG WEIGH GAUGE                               2.0
                   METAL DETECTORATEX22                               2.0
                   MICROTECH 9100F                                    2.0
                   MINIAMP                                            2.0
                   ORETRONICSIII TMD                                  5.0
                   RADEYEB20 a FLTR RJT                              11.0
                   RADIOMETRIE RM200E-M                               6.0
                   RM100 METALTHICKNESS                               5.0
                   RM120 EM STRIP                                     6.0
                   RM130 METALTHICKNESS                               5.0
                   RM200 METALTHICKNESS                               4.0
                   RM200EG THICKNESSSYS                               2.0
                   RM200EM METALTHIKNSS                               4.0
                   RM210 METALTHICKNESS                               6.0
                   RM215 METALTHICKNESS                               7.0
...                                                                   ...
Unknown            HC ANALYZER                                        1.0
                   HPLC-Colmn                                        10.0
                   HPLC-P4000                                        12.0
                   HPLC-Pump                                          2.0
                   HPLC-U3000                                         7.0
                   High Perf LR&F                                     1.0
                   ICS6000                                            2.0
                   LCMS-Altis                                         2.0
                   LCMS-OT                                           11.0
                   LN2 Cryo                                           1.0
                   LSMS                                              11.0
                   MULTIGAS CALIBRATOR                                4.0
                   Micro Centrifuge                                   5.0
                   NANODROP LITE                                     10.0
                   NANODROP ONEC                                      1.0
                   NOX ANALYZER                                       1.0
                   OZONE ANALYZER                                     4.0
                   Oven                                               1.0
                   PM 10 ANALYZER                                     5.0
                   Remote Monitoring Sy                               2.0
                   SO2 ANALYZER                                       1.0
                   SOFTWARE                                          10.0
                   Stirrer                                            1.0
                   TRACE GC                                           1.0
                   Trace GC                                           2.0
                   TraceGC-AS                                        11.0
                   ULT Freezer                                        1.0
                   UV-VIS SPECTROPHOMTR                               2.0
                   Value Enhanced LR&F                                2.0
                   iCAP6300-D                                        11.0

[645 rows x 2 columns]

In [289]:
pd.set_option("display.min_rows",100)
groupby=df.groupby(["corrected division","equipment model name"]).agg({"USD Dollars":"sum", "Ageing of the product (in years)":np.mean, "Division Name":"nunique"}).sort_values(by="USD Dollars",ascending=False)

In [290]:
df[["corrected division","equipment model name","USD Dollars","Ageing of the product (in years)","Division Name"]]

,corrected division,equipment model name,USD Dollars,Ageing of the product (in years),Division Name
26,LSI,Bio Safety Cabinet,23670.0,2.44,Anantapur Division
46,CAD,ORETRONICSIII TMD,58806.0,5.09,Anantapur Division
47,EPM,SO2 ANALYZER,93180.0,1.45,Anantapur Division
48,EPM,NOx ANALYSER 42C,89846.0,1.45,Anantapur Division
49,EPM,SO2 ANALYZER,16179.0,1.45,Anantapur Division
50,EPM,MULTIGAS CALIBRATOR,34492.0,1.45,Anantapur Division
51,EPM,NaN,47936.0,2.91,Anantapur Division
52,EPM,DUST ANALYSER BETA M,28415.0,1.45,Anantapur Division
53,EPM,DUST ANALYSER BETA M,63191.0,1.45,Anantapur Division
54,EPM,DUST ANALYSER BETA M,99821.0,1.45,Anantapur Division
55,EPM,CO ANALYZER,22433.0,1.45,Anantapur Division
56,EPM,NaN,20949.0,2.91,Anantapur Division
57,EPM,NaN,80227.0,2.91,Anantapur Division
58,CAD,ORETRONICSIII TMD,10378.0,5.09,Anantapur Division
59,EPM,CO ANALYZER,45580.0,1.45,Anantapur Division
60,EPM,NaN,18659.0,2.91,Anantapur Division
61,EPM,NaN,31241.0,2.91,Anantapur Division
62,EPM,DUST ANALYSER BETA M,68383.0,1.45,Anantapur Division
63,EPM,SO2 ANALYZER,92101.0,1.45,Anantapur Division
64,CAD,ORETRONICSIII TMD,66596.0,5.09,Anantapur Division
65,CAD,ORETRONICSIII TMD,4042.0,5.09,Anantapur Division
239,LSI,Furnace,72706.0,1.67,Anantapur Division
240,LSI,NaN,29211.0,2.64,Anantapur Division
241,MOL,UV2600,68901.0,12.33,Anantapur Division
242,LSI,Bio Safety Cabinet,19436.0,2.64,Anantapur Division
243,CMD,GC1000,21999.0,12.33,Anantapur Division
244,LSI,NaN,53129.0,2.63,Anantapur Division
493,EPM,NaN,42567.0,4.36,Anantapur Division
494,EPM,NaN,41135.0,4.49,Anantapur Division
495,EPM,NaN,81703.0,4.36,Anantapur Division
...,...,...,...,...,...
322379,CMD,GC1000,51596.0,18.36,Tamluk Division
322380,CMD,GC1000,77875.0,21.65,Tamluk Division
322381,CMD,NaN,40484.0,2.57,Tamluk Division
322382,MOL,NICOLET IS5 FTIR,99622.0,6.26,Tamluk Division
322498,EPM,M-PULSE,46003.0,5.99,Tamluk Division
322499,EPM,NaN,57047.0,2.49,Tamluk Division
322500,CMD,CERES800+,14520.0,15.50,Tamluk Division
322501,LSI,High Perf LR&F,4892.0,4.74,Tamluk Division
322502,EPM,SOLA II ANALYZER,29792.0,3.21,Tamluk Division
322503,EPM,M-PULSE,28464.0,4.34,Tamluk Division
322504,EPM,M-PULSE,77409.0,4.34,Tamluk Division
322505,EPM,NaN,44771.0,2.49,Tamluk Division
322506,EPM,SOLA II ANALYZER,32025.0,1.38,Tamluk Division
322507,EPM,M-PULSE,65273.0,5.99,Tamluk Division
322508,CMD,GC7610,58884.0,12.43,Tamluk Division
322509,LSI,High Perf LR&F,63546.0,4.74,Tamluk Division
322510,MOL,US2700,84365.0,14.50,Tamluk Division
322511,CMD,GC1000,5453.0,12.43,Tamluk Division
322512,EPM,M-PULSE,38153.0,4.34,Tamluk Division
322513,EPM,SO2 ANALYZER,38599.0,2.21,Tamluk Division
322514,EPM,NaN,18157.0,2.49,Tamluk Division
322515,CMD,GC1000,41784.0,12.43,Tamluk Division
322516,EPM,SO2 ANALYZER,87343.0,2.21,Tamluk Division
322517,EPM,M-PULSE,84140.0,6.01,Tamluk Division
322518,CMD,GC1000,18373.0,12.74,Tamluk Division
322519,CMD,iCAP7600-D,59996.0,5.52,Tamluk Division
322520,EPM,NaN,72763.0,2.21,Tamluk Division
322521,CMD,GC8610,81996.0,12.43,Tamluk Division
322522,EPM,NaN,44213.0,2.49,Tamluk Division
322523,CMD,GC1000,54441.0,12.43,Tamluk Division

In [291]:
df[["USD Dollars","Ageing of the product (in years)"]].groupby([df["corrected division"], df["equipment model name"]]).mean()

                                          USD Dollars  \
corrected division equipment model name
CAD                3500TLD READER        23632.000000
                   ALLOY ANALYZER 100G   47434.285714
                   ALLOY ANALYZER 800    54813.000000
                   AUTO SCRAP MONITOR    98332.000000
                   BELT SCALE            55325.941176
                   BELT WEIGHER          60392.000000
                   CBX ANALYZER          35595.500000
                   COAL SAMPLING SYS     55945.000000
                   COATING WEIGHT GAUGE  72837.000000
                   CQM ANALYZER          69732.500000
                   DOSIMTR GAMMA GREY    55890.210526
                   EPD BETAGAMMA GREY    54037.666667
                   EPD BLACK             21480.666667
                   EPD YELLOW            49760.000000
                   IPLUS WEBTHICKNESS    93190.500000
                   LE COTNG WEIGH GAUGE  36104.000000
                   METAL DETECTORATEX22  56579.277778
                   MICROTECH 9100F       11598.000000
                   MINIAMP               51185.562500
                   ORETRONICSIII TMD     49544.492308
                   RADEYEB20 a FLTR RJT  20609.000000
                   RADIOMETRIE RM200E-M  71648.500000
                   RM100 METALTHICKNESS  25720.333333
                   RM120 EM STRIP        97864.000000
                   RM130 METALTHICKNESS  88220.500000
                   RM200 METALTHICKNESS  62123.258065
                   RM200EG THICKNESSSYS  55367.000000
                   RM200EM METALTHIKNSS  51570.700000
                   RM210 METALTHICKNESS  56687.285714
                   RM215 METALTHICKNESS  28285.833333
...                                               ...
Unknown            HC ANALYZER           20518.000000
                   HPLC-Colmn            62835.000000
                   HPLC-P4000            49326.666667
                   HPLC-Pump             73916.000000
                   HPLC-U3000            25544.000000
                   High Perf LR&F        45712.000000
                   ICS6000               59681.500000
                   LCMS-Altis            26895.000000
                   LCMS-OT               63752.000000
                   LN2 Cryo               9320.000000
                   LSMS                  28636.000000
                   MULTIGAS CALIBRATOR   32451.000000
                   Micro Centrifuge      46826.333333
                   NANODROP LITE         11183.000000
                   NANODROP ONEC         85169.000000
                   NOX ANALYZER          10473.000000
                   OZONE ANALYZER        72739.000000
                   Oven                  74839.000000
                   PM 10 ANALYZER         7991.000000
                   Remote Monitoring Sy  61352.000000
                   SO2 ANALYZER          46078.000000
                   SOFTWARE              74539.000000
                   Stirrer               56723.400000
                   TRACE GC              10106.000000
                   Trace GC              86773.000000
                   TraceGC-AS            40630.000000
                   ULT Freezer           41484.666667
                   UV-VIS SPECTROPHOMTR  35223.000000
                   Value Enhanced LR&F   66421.000000
                   iCAP6300-D            26635.000000

                                         Ageing of the product (in years)
corrected division equipment model name
CAD                3500TLD READER                                1.820000
                   ALLOY ANALYZER 100G                           4.738571
                   ALLOY ANALYZER 800                            6.410000
                   AUTO SCRAP MONITOR                            1.870000
                   BELT SCALE                                    2.507059
                   BELT WEIGHER                                  3.160000
                   CBX ANALYZER                                  8.840000
                   COAL SAMPLING SYS                             1.750000
                   COATING WEIGHT GAUGE                          1.560000
                   CQM ANALYZER                                 14.900000
                   DOSIMTR GAMMA GREY                           11.608421
                   EPD BETAGAMMA GREY                           11.176667
                   EPD BLACK                                     2.550000
                   EPD YELLOW                                   10.600000
                   IPLUS WEBTHICKNESS                            1.450000
                   LE COTNG WEIGH GAUGE                          2.236667
                   METAL DETECTORATEX22                          2.148889
                   MICROTECH 9100F                               1.730000
                   MINIAMP                                       2.187500
                   ORETRONICSIII TMD                             5.188923
                   RADEYEB20 a FLTR RJT                         11.140000
                   RADIOMETRIE RM200E-M                          6.105000
                   RM100 METALTHICKNESS                          5.115000
                   RM120 EM STRIP                                5.580000
                   RM130 METALTHICKNESS                          5.455000
                   RM200 METALTHICKNESS                          3.820968
                   RM200EG THICKNESSSYS                          1.505000
                   RM200EM METALTHIKNSS                          4.292000
                   RM210 METALTHICKNESS                          5.547143
                   RM215 METALTHICKNESS                          7.185000
...                                                                   ...
Unknown            HC ANALYZER                                   1.360000
                   HPLC-Colmn                                    9.590000
                   HPLC-P4000                                   11.943333
                   HPLC-Pump                                     1.760000
                   HPLC-U3000                                    6.710000
                   High Perf LR&F                                1.360000
                   ICS6000                                       2.285000
                   LCMS-Altis                                    2.170000
                   LCMS-OT                                      11.490000
                   LN2 Cryo                                      1.340000
                   LSMS                                         11.250000
                   MULTIGAS CALIBRATOR                           3.570000
                   Micro Centrifuge                              5.200000
                   NANODROP LITE                                 9.760000
                   NANODROP ONEC                                 1.480000
                   NOX ANALYZER                                  1.370000
                   OZONE ANALYZER                                4.360000
                   Oven                                          1.250000
                   PM 10 ANALYZER                                4.860000
                   Remote Monitoring Sy                          1.700000
                   SO2 ANALYZER                                  1.370000
                   SOFTWARE                                     10.290000
                   Stirrer                                       1.370000
                   TRACE GC                                      1.330000
                   Trace GC                                      1.930000
                   TraceGC-AS                                   11.050000
                   ULT Freezer                                   1.396667
                   UV-VIS SPECTROPHOMTR                          1.640000
                   Value Enhanced LR&F                           1.530000
                   iCAP6300-D                                   10.825000

[645 rows x 2 columns]